In [3]:
import pandas as pd

In [4]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# Cargar los datasets

df_delitos = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/interim/delitos_propiedad_departamento_anual.csv")
df_geo = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/prov_departamentos_nombres.csv")

print("df_delitos:", df_delitos.shape)
print("df_geo:", df_geo.shape)

print("\nColumnas df_delitos:")
print(df_delitos.columns.tolist())

print("\nColumnas df_geo:")
print(df_geo.columns.tolist())

print(df_delitos.head())
df_geo.head()

df_delitos: (13342, 7)
df_geo: (527, 5)

Columnas df_delitos:
['provincia_id', 'provincia_nombre', 'departamento_id', 'departamento_nombre', 'anio', 'delitos_propiedad_hechos', 'delitos_propiedad_victimas']

Columnas df_geo:
['redcode', 'nprov_0', 'ndpto_1', 'redcoden_2', 'Unnamed: 4']
   provincia_id                 provincia_nombre  departamento_id  \
0             2  Ciudad Autónoma de Buenos Aires             2001
1             2  Ciudad Autónoma de Buenos Aires             2001
2             2  Ciudad Autónoma de Buenos Aires             2001
3             2  Ciudad Autónoma de Buenos Aires             2001
4             2  Ciudad Autónoma de Buenos Aires             2001

  departamento_nombre  anio  delitos_propiedad_hechos  \
0            Comuna 1  2000                         0
1            Comuna 1  2001                         0
2            Comuna 1  2002                         0
3            Comuna 1  2003                         0
4            Comuna 1  2004                         0

   delitos_propiedad_victimas
0                         0.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0

   redcode nprov_0   ndpto_1  redcoden_2  Unnamed: 4
0     2007    Caba  Comuna 1        2007         NaN
1     2014    Caba  Comuna 2        2014         NaN
2     2021    Caba  Comuna 3        2021         NaN
3     2028    Caba  Comuna 4        2028         NaN
4     2035    Caba  Comuna 5        2035         NaN

In [6]:
# Seleccionar solo las columnas necesarias y renombrarlas para facilitar el merge
df_geo = df_geo[["redcode", "nprov_0", "ndpto_1"]]

df_geo = df_geo.rename(columns={
    "redcode": "departamento_id_geo",
    "nprov_0": "provincia_geo",
    "ndpto_1": "departamento_geo"
})

df_geo.head()

   departamento_id_geo provincia_geo departamento_geo
0                 2007          Caba         Comuna 1
1                 2014          Caba         Comuna 2
2                 2021          Caba         Comuna 3
3                 2028          Caba         Comuna 4
4                 2035          Caba         Comuna 5

In [7]:
# Normalizar los nombres de provincias y departamentos para facilitar el merge
df_delitos["provincia_nombre"] = df_delitos["provincia_nombre"].str.lower().str.strip()
df_delitos["departamento_nombre"] = df_delitos["departamento_nombre"].str.lower().str.strip()

df_geo["provincia_geo"] = df_geo["provincia_geo"].str.lower().str.strip()
df_geo["departamento_geo"] = df_geo["departamento_geo"].str.lower().str.strip()

In [8]:
# Realizar el merge entre ambos datasets
df_check = df_delitos.merge(
    df_geo,
    left_on=["provincia_nombre", "departamento_nombre"],
    right_on=["provincia_geo", "departamento_geo"],
    how="left"
)

In [9]:
print (df_check.shape)
df_check.head()

(13342, 10)

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,delitos_propiedad_victimas,departamento_id_geo,provincia_geo,departamento_geo
0,2,ciudad autónoma de buenos aires,2001,comuna 1,2000,0,0.0,NaN,NaN,NaN
1,2,ciudad autónoma de buenos aires,2001,comuna 1,2001,0,0.0,NaN,NaN,NaN
2,2,ciudad autónoma de buenos aires,2001,comuna 1,2002,0,0.0,NaN,NaN,NaN
3,2,ciudad autónoma de buenos aires,2001,comuna 1,2003,0,0.0,NaN,NaN,NaN
4,2,ciudad autónoma de buenos aires,2001,comuna 1,2004,0,0.0,NaN,NaN,NaN

In [10]:
# Identificar filas sin match
import unicodedata

def normalizar_texto(s):
    if pd.isna(s):
        return s
    s = str(s).lower().strip()
    s = ''.join(
        c for c in unicodedata.normalize('NFKD', s)
        if not unicodedata.combining(c)
    )
    s = ' '.join(s.split())
    return s

# normalizar columnas
df_delitos["provincia_key"] = df_delitos["provincia_nombre"].apply(normalizar_texto)
df_delitos["departamento_key"] = df_delitos["departamento_nombre"].apply(normalizar_texto)

df_geo["provincia_key"] = df_geo["provincia_geo"].apply(normalizar_texto)
df_geo["departamento_key"] = df_geo["departamento_geo"].apply(normalizar_texto)

# armonizar provincias conocidas
df_delitos["provincia_key"] = df_delitos["provincia_key"].replace({
    "ciudad autonoma de buenos aires": "caba",
    "tierra del fuego, antartida e islas del atlantico sur": "tierra del fuego"
})

df_geo["provincia_key"] = df_geo["provincia_key"].replace({
    "ciudad autonoma de buenos aires": "caba",
    "tierra del fuego, antartida e islas del atlantico sur": "tierra del fuego"
})

In [11]:
# Rehacer el merge con las claves normalizadas
df_check = df_delitos.merge(
    df_geo,
    on=["provincia_key", "departamento_key"],
    how="left",
    suffixes=("", "_geo")
)

In [12]:
# Verificar filas sin match
df_check[df_check["departamento_id_geo"].isna()][
    ["provincia_nombre", "departamento_nombre"]
].drop_duplicates()

,provincia_nombre,departamento_nombre
375,ciudad autónoma de buenos aires,departamento sin determinar
852,buenos aires,cañuelas
1027,buenos aires,coronel de marina l. rosales
1302,buenos aires,esteban echeverría
1902,buenos aires,ituzaingó
...,...,...
12442,santiago del estero,juan f. ibarra
12792,santiago del estero,departamento sin determinar
12817,tucumán,burruyacú
13242,tucumán,departamento sin determinar
13317,"tierra del fuego, antártida e islas del atlánt...",departamento sin determinar

In [13]:
# Analizar filas sin match
faltantes = df_check[df_check["departamento_id_geo"].isna()][
    ["provincia_nombre", "departamento_nombre", "provincia_key", "departamento_key"]
].drop_duplicates()

sin_determinar = faltantes[
    faltantes["departamento_key"] == "departamento sin determinar"
]

no_macheados_reales = faltantes[
    faltantes["departamento_key"] != "departamento sin determinar"
]

print("Sin determinar:", sin_determinar.shape)
print("No macheados reales:", no_macheados_reales.shape)

no_macheados_reales.sort_values(["provincia_nombre", "departamento_nombre"])

Sin determinar: (24, 4)
No macheados reales: (41, 4)

,provincia_nombre,departamento_nombre,provincia_key,departamento_key
852,buenos aires,cañuelas,buenos aires,canuelas
1027,buenos aires,coronel de marina l. rosales,buenos aires,coronel de marina l. rosales
1302,buenos aires,esteban echeverría,buenos aires,esteban echeverria
1902,buenos aires,ituzaingó,buenos aires,ituzaingo
1927,buenos aires,josé c. paz,buenos aires,jose c. paz
2192,buenos aires,lobería,buenos aires,loberia
2267,buenos aires,luján,buenos aires,lujan
2642,buenos aires,olavarría,buenos aires,olavarria
3890,catamarca,belén,catamarca,belen
3915,catamarca,capayán,catamarca,capayan
4090,catamarca,santa maría,catamarca,santa maria
5690,chaco,fray justo santa maría de oro,chaco,fray justo santa maria de oro
5765,chaco,general güemes,chaco,general guemes
5940,chaco,o' higgins,chaco,o' higgins
5165,corrientes,ituzaingó,corrientes,ituzaingo
5215,corrientes,mburucuyá,corrientes,mburucuya
4715,córdoba,santa maría,cordoba,santa maria
6839,entre ríos,nogoyá,entre rios,nogoya
7414,jujuy,palpalá,jujuy,palpala
7714,la pampa,centro (santa rosa),la pampa,centro (santa rosa)
7826,la pampa,chicalcó,la pampa,chicalco
7736,la pampa,norte (general pico),la pampa,norte (general pico)
7780,la pampa,oeste (25 de mayo),la pampa,oeste (25 de mayo)
7849,la pampa,quemú ouemú,la pampa,quemu ouemu
7758,la pampa,sur (general acha),la pampa,sur (general acha)
7967,la rioja,coronel felipe varela,la rioja,coronel felipe varela
8067,la rioja,general angel v. peñaloza,la rioja,general angel v. penaloza
8117,la rioja,general juan f. quiroga,la rioja,general juan f. quiroga
8167,la rioja,general ocampo,la rioja,general ocampo
8567,mendoza,luján de cuyo,mendoza,lujan de cuyo
8617,mendoza,malargüe,mendoza,malargue
8767,mendoza,tunuyán,mendoza,tunuyan
8842,misiones,apóstoles,misiones,apostoles
9042,misiones,iguazú,misiones,iguazu
9092,misiones,libertador grl. san martín,misiones,libertador grl. san martin
10217,salta,general güemes,salta,general guemes
10242,salta,grl. josé de san martín,salta,grl. jose de san martin
11342,san luis,la capital,san luis,la capital
11467,santa cruz,güer aike,santa cruz,guer aike
12442,santiago del estero,juan f. ibarra,santiago del estero,juan f. ibarra
12817,tucumán,burruyacú,tucuman,burruyacu

In [14]:
# Eliminar filas sin determinar
df_delitos = df_delitos[
    df_delitos["departamento_key"] != "departamento sin determinar"
].copy()

df_delitos.shape

(12742, 9)

In [15]:
# Rehacer el merge con las claves normalizadas
df_check = df_delitos.merge(
    df_geo,
    on=["provincia_key", "departamento_key"],
    how="left"
)

In [16]:
# Verificar filas sin match
faltantes_finales = df_check[df_check["departamento_id_geo"].isna()][
    ["provincia_nombre", "departamento_nombre"]
].drop_duplicates()

print("Faltantes finales:", faltantes_finales.shape)
faltantes_finales.sort_values(["provincia_nombre", "departamento_nombre"])

Faltantes finales: (41, 2)

          provincia_nombre            departamento_nombre
827           buenos aires                       cañuelas
1002          buenos aires   coronel de marina l. rosales
1277          buenos aires             esteban echeverría
1877          buenos aires                      ituzaingó
1902          buenos aires                    josé c. paz
2167          buenos aires                        lobería
2242          buenos aires                          luján
2617          buenos aires                      olavarría
3840             catamarca                          belén
3865             catamarca                        capayán
4040             catamarca                    santa maría
5565                 chaco  fray justo santa maría de oro
5640                 chaco                 general güemes
5815                 chaco                     o' higgins
5065            corrientes                      ituzaingó
5115            corrientes                      mburucuyá
4640               córdoba                    santa maría
6664            entre ríos                         nogoyá
7189                 jujuy                        palpalá
7464              la pampa            centro (santa rosa)
7576              la pampa                       chicalcó
7486              la pampa           norte (general pico)
7530              la pampa             oeste (25 de mayo)
7599              la pampa                    quemú ouemú
7508              la pampa             sur (general acha)
7692              la rioja          coronel felipe varela
7792              la rioja      general angel v. peñaloza
7842              la rioja        general juan f. quiroga
7892              la rioja                 general ocampo
8267               mendoza                  luján de cuyo
8317               mendoza                       malargüe
8467               mendoza                        tunuyán
8517              misiones                      apóstoles
8717              misiones                         iguazú
8767              misiones     libertador grl. san martín
9817                 salta                 general güemes
9842                 salta        grl. josé de san martín
10892             san luis                     la capital
10992           santa cruz                      güer aike
11917  santiago del estero                 juan f. ibarra
12267              tucumán                      burruyacú

In [17]:
# Importamos la función que permite buscar strings parecidos
from difflib import get_close_matches

# Lista vacía donde vamos a guardar todas las sugerencias
sugerencias = []

# Recorremos TODOS los faltantes (no solo los primeros 10)
for _, row in faltantes.iterrows():

    # Tomamos la provincia normalizada del dataset de delitos
    prov = row["provincia_key"]

    # Tomamos el nombre del departamento normalizado del dataset de delitos
    dpto = row["departamento_key"]

    # Filtramos df_geo para quedarnos SOLO con esa provincia
    # y extraemos la lista de nombres de departamentos posibles
    candidatos = df_geo[
        df_geo["provincia_key"] == prov
    ]["departamento_key"].dropna().unique().tolist()

    # Buscamos coincidencias aproximadas entre el nombre de delitos y los de df_geo
    # n=3 → máximo 3 sugerencias
    # cutoff=0.6 → nivel mínimo de similitud (0 a 1)
    matches = get_close_matches(dpto, candidatos, n=3, cutoff=0.8)

    # Guardamos la información en un diccionario
    sugerencias.append({
        "provincia_nombre": row["provincia_nombre"],
        "departamento_nombre": row["departamento_nombre"],
        "departamento_key": dpto,
        "sugerencia_1": matches[0] if len(matches) > 0 else None,
        "sugerencia_2": matches[1] if len(matches) > 1 else None,
        "sugerencia_3": matches[2] if len(matches) > 2 else None,
    })

# Convertimos la lista de diccionarios en un DataFrame
df_sugerencias = pd.DataFrame(sugerencias)

# Ordenamos para que sea más fácil de leer
df_sugerencias = df_sugerencias.sort_values(
    ["provincia_nombre", "departamento_nombre"]
)

# Mostramos el resultado
df_sugerencias.head(25)

,provincia_nombre,departamento_nombre,departamento_key,sugerencia_1,sugerencia_2,sugerencia_3
1,buenos aires,cañuelas,canuelas,ca uelas,None,None
2,buenos aires,coronel de marina l. rosales,coronel de marina l. rosales,coronel de marina leonardo rosales,None,None
9,buenos aires,departamento sin determinar,departamento sin determinar,None,None,None
3,buenos aires,esteban echeverría,esteban echeverria,esteban echeverrka,None,None
4,buenos aires,ituzaingó,ituzaingo,ituzaingˇ,None,None
5,buenos aires,josé c. paz,jose c. paz,jost c. paz,None,None
6,buenos aires,lobería,loberia,loberka,None,None
7,buenos aires,luján,lujan,lujsn,None,None
8,buenos aires,olavarría,olavarria,olavarrka,None,None
10,catamarca,belén,belen,belun,None,None
11,catamarca,capayán,capayan,capaysn,None,None
13,catamarca,departamento sin determinar,departamento sin determinar,None,None,None
12,catamarca,santa maría,santa maria,santa marka,None,None
22,chaco,departamento sin determinar,departamento sin determinar,None,None,None
19,chaco,fray justo santa maría de oro,fray justo santa maria de oro,fray justo santa marka de oro,None,None
20,chaco,general güemes,general guemes,general głemes,None,None
21,chaco,o' higgins,o' higgins,o'higgins,None,None
23,chubut,departamento sin determinar,departamento sin determinar,None,None,None
0,ciudad autónoma de buenos aires,departamento sin determinar,departamento sin determinar,None,None,None
18,corrientes,departamento sin determinar,departamento sin determinar,None,None,None
16,corrientes,ituzaingó,ituzaingo,ituzaingˇ,None,None
17,corrientes,mburucuyá,mburucuya,mburucuys,None,None
15,córdoba,departamento sin determinar,departamento sin determinar,None,None,None
14,córdoba,santa maría,santa maria,santa marka,None,None
25,entre ríos,departamento sin determinar,departamento sin determinar,None,None,None

In [18]:
# Construir diccionario automático usando la mejor sugerencia encontrada
correcciones_auto = {
    row["departamento_key"]: row["sugerencia_1"]
    for _, row in df_sugerencias.iterrows()
    if pd.notna(row["sugerencia_1"])
}

In [19]:
# Aplicar correcciones automáticas
df_delitos["departamento_key"] = df_delitos["departamento_key"].replace(correcciones_auto)

In [20]:
# Rehacer el merge con las claves normalizadas
df_check = df_delitos.merge(
    df_geo,
    on=["provincia_key", "departamento_key"],
    how="left"
)

In [21]:
# Verificar filas sin match
faltantes_finales = df_check[df_check["departamento_id_geo"].isna()][
    ["provincia_nombre", "departamento_nombre"]
].drop_duplicates()

print("Faltantes finales:", faltantes_finales.shape)
faltantes_finales.sort_values(["provincia_nombre", "departamento_nombre"])

Faltantes finales: (7, 2)

      provincia_nombre        departamento_nombre
7464          la pampa        centro (santa rosa)
7486          la pampa       norte (general pico)
7530          la pampa         oeste (25 de mayo)
7508          la pampa         sur (general acha)
7792          la rioja  general angel v. peñaloza
7892          la rioja             general ocampo
10892         san luis                 la capital

In [22]:
# Analizar caso específico de La Pampa
df_geo[df_geo["provincia_key"] == "la pampa"][
    ["provincia_geo", "departamento_geo", "departamento_key"]
].sort_values("departamento_geo")

    provincia_geo departamento_geo departamento_key
299      la pampa          atreucó          atreuco
300      la pampa      caleu caleu      caleu caleu
301      la pampa          capital          capital
302      la pampa          catriló          catrilo
305      la pampa         chalileo         chalileo
306      la pampa       chapaleufú       chapaleufu
307      la pampa        chical co        chical co
303      la pampa          conhelo          conhelo
304      la pampa           curacó           curaco
308      la pampa        guatraché        guatrache
309      la pampa            hucal            hucal
310      la pampa     lihuel calel     lihuel calel
311      la pampa    limay mahuida    limay mahuida
312      la pampa         loventué         loventue
313      la pampa           maracó           maraco
314      la pampa           puelén           puelen
315      la pampa      quemú quemú      quemu quemu
316      la pampa           rancul           rancul
317      la pampa          realicó          realico
318      la pampa             toay             toay
319      la pampa           trenel           trenel
320      la pampa          utracán          utracan

In [23]:
#  Analizar departamentos de La Pampa en el dataset de delitos
df_delitos[
    df_delitos["provincia_nombre"] == "la pampa"
]["departamento_nombre"].drop_duplicates().sort_values()

7802                 atreucó
7805             caleu caleu
7808                 capital
7811                 catriló
7714     centro (santa rosa)
7820                chalileo
7823              chapaleufú
7826                chicalcó
7814                 conhelo
7817                  curacó
7828               guatraché
7831                   hucal
7834            lihuel calel
7837           limay mahuida
7840                loventué
7843                  maracó
7736    norte (general pico)
7780      oeste (25 de mayo)
7846                  puelén
7849             quemú ouemú
7852                  rancul
7855                 realicó
7758      sur (general acha)
7858                    toay
7861                  trenel
7864                 utracán
Name: departamento_nombre, dtype: object

# cerrando dataset base para tasas

In [24]:
# Conclusión: no hay forma de hacer un match correcto para estos casos, por lo que se van a excluir de la base de tasas (pero se mantienen en la base de delitos para futuros análisis)
df_tasas_base = df_check.copy()

df_tasas_base = df_tasas_base[
    df_tasas_base["departamento_key"] != "departamento sin determinar"
].copy()

casos_excluir_tasas = [
    ("la pampa", "centro (santa rosa)"),
    ("la pampa", "norte (general pico)"),
    ("la pampa", "oeste (25 de mayo)"),
    ("la pampa", "sur (general acha)"),
    ("san luis", "la capital"),
]

mask_lp = df_tasas_base.apply(
    lambda row: (row["provincia_key"], row["departamento_key"]) in casos_excluir_tasas,
    axis=1
)

df_tasas_base = df_tasas_base[~mask_lp].copy()

df_tasas_base = df_tasas_base[
    df_tasas_base["departamento_id_geo"].notna()
].copy()

print("Base para tasas:", df_tasas_base.shape)
df_tasas_base.head()

Base para tasas: (12579, 12)

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,delitos_propiedad_victimas,provincia_key,departamento_key,departamento_id_geo,provincia_geo,departamento_geo
0,2,ciudad autónoma de buenos aires,2001,comuna 1,2000,0,0.0,caba,comuna 1,2007.0,caba,comuna 1
1,2,ciudad autónoma de buenos aires,2001,comuna 1,2001,0,0.0,caba,comuna 1,2007.0,caba,comuna 1
2,2,ciudad autónoma de buenos aires,2001,comuna 1,2002,0,0.0,caba,comuna 1,2007.0,caba,comuna 1
3,2,ciudad autónoma de buenos aires,2001,comuna 1,2003,0,0.0,caba,comuna 1,2007.0,caba,comuna 1
4,2,ciudad autónoma de buenos aires,2001,comuna 1,2004,0,0.0,caba,comuna 1,2007.0,caba,comuna 1

In [25]:
df_tasas_base.isna().sum()

provincia_id                  0
provincia_nombre              0
departamento_id               0
departamento_nombre           0
anio                          0
delitos_propiedad_hechos      0
delitos_propiedad_victimas    0
provincia_key                 0
departamento_key              0
departamento_id_geo           0
provincia_geo                 0
departamento_geo              0
dtype: int64

# cargando dataset poblacion

In [26]:
# Guardar base final para tasas
df_pob = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/poblacion_departamentos_2022.csv")
df_pob.head()

   redcode  count_persona_0  Unnamed: 2
0     2007           221001         NaN
1     2014           160609         NaN
2     2021           193537         NaN
3     2028           227024         NaN
4     2035           192449         NaN

In [27]:

df_pob.columns

Index(['redcode', 'count_persona_0', 'Unnamed: 2'], dtype='object')

In [28]:
# Seleccionar solo las columnas necesarias y renombrarlas para facilitar el merge
df_pob = df_pob[["redcode", "count_persona_0"]].rename(columns={
    "redcode": "departamento_id_geo",
    "count_persona_0": "poblacion_2022"
})

In [29]:
df_pob.head()

   departamento_id_geo  poblacion_2022
0                 2007          221001
1                 2014          160609
2                 2021          193537
3                 2028          227024
4                 2035          192449

# Merge con poblacion

In [30]:
df_tasas = df_tasas_base.merge(
    df_pob,
    on="departamento_id_geo",
    how="left"
)

In [31]:
df_tasas["poblacion_2022"].isna().sum()

np.int64(0)

In [32]:

df_tasas["tasa_delitos_propiedad_100k"] = (
    df_tasas["delitos_propiedad_hechos"] / df_tasas["poblacion_2022"]
) * 100000

In [33]:
# Mostrar resultado final
df_tasas[[
    "provincia_nombre",
    "departamento_nombre",
    "anio",
    "delitos_propiedad_hechos",
    "poblacion_2022",
    "tasa_delitos_propiedad_100k"
]].head()

,provincia_nombre,departamento_nombre,anio,delitos_propiedad_hechos,poblacion_2022,tasa_delitos_propiedad_100k
0,ciudad autónoma de buenos aires,comuna 1,2000,0,221001,0.0
1,ciudad autónoma de buenos aires,comuna 1,2001,0,221001,0.0
2,ciudad autónoma de buenos aires,comuna 1,2002,0,221001,0.0
3,ciudad autónoma de buenos aires,comuna 1,2003,0,221001,0.0
4,ciudad autónoma de buenos aires,comuna 1,2004,0,221001,0.0

In [34]:
# Calcular tasa por cada 100 habitantes (en porcentaje)
df_tasas["tasa_delitos_propiedad_pct"] = (
    df_tasas["delitos_propiedad_hechos"] / df_tasas["poblacion_2022"]
) * 100

In [35]:
# Mostrar departamentos con mayor tasa por cada 100k habitantes
df_tasas[[
    "provincia_nombre",
    "departamento_nombre",
    "anio",
    "delitos_propiedad_hechos",
    "poblacion_2022",
    "tasa_delitos_propiedad_100k"
]].sort_values("tasa_delitos_propiedad_100k", ascending=False).head(20)

,provincia_nombre,departamento_nombre,anio,delitos_propiedad_hechos,poblacion_2022,tasa_delitos_propiedad_100k
3474,buenos aires,tordillo,2009,1600,2528,63291.139241
2061,buenos aires,laprida,2009,2732,11496,23764.787752
3599,buenos aires,tres lomas,2009,1350,9090,14851.485149
7943,mendoza,capital,2014,16223,123715,13113.203734
7944,mendoza,capital,2015,16038,123715,12963.666492
7938,mendoza,capital,2009,15673,123715,12668.633553
7941,mendoza,capital,2012,15630,123715,12633.876248
7942,mendoza,capital,2013,15053,123715,12167.481712
7940,mendoza,capital,2011,14991,123715,12117.366528
7939,mendoza,capital,2010,14787,123715,11952.471406
24,ciudad autónoma de buenos aires,comuna 1,2024,24297,221001,10994.067900
23,ciudad autónoma de buenos aires,comuna 1,2023,23541,221001,10651.988000
2924,buenos aires,ramallo,2009,4149,39648,10464.588378
7945,mendoza,capital,2016,12514,123715,10115.184092
19,ciudad autónoma de buenos aires,comuna 1,2019,21721,221001,9828.462315
7952,mendoza,capital,2023,11984,123715,9686.780099
22,ciudad autónoma de buenos aires,comuna 1,2022,20959,221001,9483.667495
7951,mendoza,capital,2022,10924,123715,8829.972113
7953,mendoza,capital,2024,10863,123715,8780.665239
2451,buenos aires,monte,2009,2082,24616,8457.913552

# Guardado de datasets

## delitos

In [36]:
cols_real = [
    "provincia_id", "provincia_nombre",
    "departamento_id", "departamento_nombre",
    "anio", "delitos_propiedad_hechos"
]

df_delitos_real = df_delitos[cols_real].copy()

## Tasas

In [37]:
cols_tasas = [
    "provincia_id", "provincia_nombre",
    "departamento_id", "departamento_nombre",
    "anio", "delitos_propiedad_hechos",
    "poblacion_2022",
    "tasa_delitos_propiedad_100k",
    "tasa_delitos_propiedad_pct"
]

df_tasas_final = df_tasas[cols_tasas].copy()

In [38]:
df_delitos_real.to_csv(
    r"C:\Users\Marcos\Ciencia datos e inteligencia artificial\SEXTO SEMESTRE\PP3\Copia_pre_proyecto\data\processed\delitos_propiedad_departamento_anual_real.csv",
    index=False
)

df_tasas_final.to_csv(
    r"C:\Users\Marcos\Ciencia datos e inteligencia artificial\SEXTO SEMESTRE\PP3\Copia_pre_proyecto\data\processed\delitos_propiedad_departamento_anual_tasas.csv",
    index=False
)

# MERGE CON EL RESTO DE LAS VARIABLES

In [39]:
 # Carga de datasets
delitos_propiedad_departamento_anual_real = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/delitos_propiedad_departamento_anual_real.csv")
delitos_propiedad_departamento_anual_tasas = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/delitos_propiedad_departamento_anual_tasas.csv")
cbt_variacion_anual = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/cbt_variacion_anual.csv")
empleo_const_anual = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/empleo_const_anual.csv")
ipc= pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/ipc.csv")
ipim_variacion_anual = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/ipim_variacion_anual.csv")
salarios_variacion_anual = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/salarios_variacion_anual.csv")
variacion_accesos_internet_provincias_anual = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/variacion_accesos_internet_provincias_anual.csv")

In [40]:
print(delitos_propiedad_departamento_anual_real.columns.to_list())
print(delitos_propiedad_departamento_anual_tasas.columns.to_list())
print(cbt_variacion_anual.columns.to_list())
print(empleo_const_anual.columns.to_list())
print(ipc.columns.to_list())
print(ipim_variacion_anual.columns.to_list())
print(salarios_variacion_anual.columns.to_list())
print(variacion_accesos_internet_provincias_anual.columns.to_list())

['provincia_id', 'provincia_nombre', 'departamento_id', 'departamento_nombre', 'anio', 'delitos_propiedad_hechos']
['provincia_id', 'provincia_nombre', 'departamento_id', 'departamento_nombre', 'anio', 'delitos_propiedad_hechos', 'poblacion_2022', 'tasa_delitos_propiedad_100k', 'tasa_delitos_propiedad_pct']
['Unnamed: 0', 'anio', 'variacion_anual_cbt']
['Unnamed: 0', 'anio', 'variacion_empleo_const_pct']
['region', 'anio', 'Indice_IPC']
['anio', 'mes', 'variacion_anual_ipim']
['anio', 'variacion_anual_salarios_pct']
['jurisdiccion', 'anio', 'variacion_acceso_internet_pct']

In [41]:
# Crear diccionario provincia → región . Para agregar la columna de región a los datasets de delitos y poder mergear correctamente con IPC
map_provincia_region = {
    "ciudad autónoma de buenos aires": "GBA",
    "buenos aires": "Pampeana",
    "córdoba": "Pampeana",
    "santa fe": "Pampeana",
    "entre ríos": "Pampeana",
    "la pampa": "Pampeana",

    "mendoza": "Cuyo",
    "san juan": "Cuyo",
    "san luis": "Cuyo",

    "corrientes": "Noreste",
    "chaco": "Noreste",
    "formosa": "Noreste",
    "misiones": "Noreste",

    "catamarca": "Noroeste",
    "tucumán": "Noroeste",
    "salta": "Noroeste",
    "jujuy": "Noroeste",
    "la rioja": "Noroeste",
    "santiago del estero": "Noroeste",

    "neuquén": "Patagonia",
    "río negro": "Patagonia",
    "chubut": "Patagonia",
    "santa cruz": "Patagonia",
    "tierra del fuego, antártida e islas del atlántico sur": "Patagonia"
}

In [42]:
# Agrego columna de región a los datasets de delitos
delitos_propiedad_departamento_anual_real["region"] = delitos_propiedad_departamento_anual_real["provincia_nombre"].map(map_provincia_region)

# Valido que se haya agregado correctamente
delitos_propiedad_departamento_anual_real["region"].isna().sum()

np.int64(0)

In [43]:
# Agrego columna de región a los datasets de delitos
delitos_propiedad_departamento_anual_tasas["region"] = delitos_propiedad_departamento_anual_tasas["provincia_nombre"].map(map_provincia_region)

# Valido que se haya agregado correctamente
delitos_propiedad_departamento_anual_tasas["region"].isna().sum()

np.int64(0)

In [44]:
delitos_propiedad_departamento_anual_tasas.shape

(12579, 10)

In [45]:
# Elimino las columnas unnamed de los dataserts cbt_variacion_anual y empleo_const_anual (que solo fue un id creado al guardar el csv, no es información relevante)
cbt_variacion_anual = cbt_variacion_anual.drop(columns=["Unnamed: 0"], errors="ignore")
empleo_const_anual = empleo_const_anual.drop(columns=["Unnamed: 0"], errors="ignore")

In [46]:
# Inicio el MERGE

df_final = delitos_propiedad_departamento_anual_tasas.copy()

In [47]:
df_final.shape

(12579, 10)

In [48]:
df_final.columns

Index(['provincia_id', 'provincia_nombre', 'departamento_id',
       'departamento_nombre', 'anio', 'delitos_propiedad_hechos',
       'poblacion_2022', 'tasa_delitos_propiedad_100k',
       'tasa_delitos_propiedad_pct', 'region'],
      dtype='object')

In [49]:
# Internet por provincia
df_final = df_final.merge(
    variacion_accesos_internet_provincias_anual,
    left_on=["provincia_nombre", "anio"],
    right_on=["jurisdiccion", "anio"],
    how="left"
)

df_final.columns.to_list()

['provincia_id',
 'provincia_nombre',
 'departamento_id',
 'departamento_nombre',
 'anio',
 'delitos_propiedad_hechos',
 'poblacion_2022',
 'tasa_delitos_propiedad_100k',
 'tasa_delitos_propiedad_pct',
 'region',
 'jurisdiccion',
 'variacion_acceso_internet_pct']

In [50]:
# IPC por region
df_final = df_final.merge(
    ipc,
    on=["region", "anio"],
    how="left"
)
df_final.columns.to_list()

['provincia_id',
 'provincia_nombre',
 'departamento_id',
 'departamento_nombre',
 'anio',
 'delitos_propiedad_hechos',
 'poblacion_2022',
 'tasa_delitos_propiedad_100k',
 'tasa_delitos_propiedad_pct',
 'region',
 'jurisdiccion',
 'variacion_acceso_internet_pct',
 'Indice_IPC']

In [51]:
# Variables macro (solo por año, no por provincia porque no tengo datos provinciales para todas las variables macro)

df_final = df_final.merge(salarios_variacion_anual, on="anio", how="left")
df_final = df_final.merge(cbt_variacion_anual, on="anio", how="left")
df_final = df_final.merge(empleo_const_anual, on="anio", how="left")
df_final = df_final.merge(ipim_variacion_anual, on="anio", how="left")
df_final.columns.to_list()

['provincia_id',
 'provincia_nombre',
 'departamento_id',
 'departamento_nombre',
 'anio',
 'delitos_propiedad_hechos',
 'poblacion_2022',
 'tasa_delitos_propiedad_100k',
 'tasa_delitos_propiedad_pct',
 'region',
 'jurisdiccion',
 'variacion_acceso_internet_pct',
 'Indice_IPC',
 'variacion_anual_salarios_pct',
 'variacion_anual_cbt',
 'variacion_empleo_const_pct',
 'mes',
 'variacion_anual_ipim']

In [52]:
# Elimino columna "jurisdiccion" con informacion duplicada de "provincia_nombre"
df_final = df_final.drop(columns=["jurisdiccion"], errors="ignore")

In [53]:
print(df_final.shape)
print(df_final.columns.tolist())
df_final.head()

(12579, 17)
['provincia_id', 'provincia_nombre', 'departamento_id', 'departamento_nombre', 'anio', 'delitos_propiedad_hechos', 'poblacion_2022', 'tasa_delitos_propiedad_100k', 'tasa_delitos_propiedad_pct', 'region', 'variacion_acceso_internet_pct', 'Indice_IPC', 'variacion_anual_salarios_pct', 'variacion_anual_cbt', 'variacion_empleo_const_pct', 'mes', 'variacion_anual_ipim']

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,poblacion_2022,tasa_delitos_propiedad_100k,tasa_delitos_propiedad_pct,region,variacion_acceso_internet_pct,Indice_IPC,variacion_anual_salarios_pct,variacion_anual_cbt,variacion_empleo_const_pct,mes,variacion_anual_ipim
0,2,ciudad autónoma de buenos aires,2001,comuna 1,2000,0,221001,0.0,0.0,GBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,ciudad autónoma de buenos aires,2001,comuna 1,2001,0,221001,0.0,0.0,GBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,ciudad autónoma de buenos aires,2001,comuna 1,2002,0,221001,0.0,0.0,GBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,ciudad autónoma de buenos aires,2001,comuna 1,2003,0,221001,0.0,0.0,GBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,ciudad autónoma de buenos aires,2001,comuna 1,2004,0,221001,0.0,0.0,GBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df_final.isna().sum().sort_values(ascending=False)

Indice_IPC                       12579
variacion_acceso_internet_pct    12579
variacion_anual_cbt               8507
variacion_anual_salarios_pct      8507
variacion_empleo_const_pct        8006
variacion_anual_ipim              8006
mes                               7505
provincia_id                         0
provincia_nombre                     0
tasa_delitos_propiedad_pct           0
tasa_delitos_propiedad_100k          0
poblacion_2022                       0
delitos_propiedad_hechos             0
anio                                 0
departamento_nombre                  0
departamento_id                      0
region                               0
dtype: int64

In [55]:
df_final.duplicated(
    subset=["provincia_nombre", "departamento_nombre", "anio"]
).sum()

np.int64(0)

In [56]:
df_final.describe().T

,count,mean,std,min,25%,50%,75%,max
provincia_id,12579.0,36.083472,29.401261,2.000000,6.000000,26.000000,62.000000,9.400000e+01
departamento_id,12579.0,36252.861197,29298.990980,2001.000000,6728.000000,26077.000000,62070.000000,9.401400e+04
anio,12579.0,2012.061929,7.234970,2000.000000,2006.000000,2012.000000,2018.000000,2.024000e+03
delitos_propiedad_hechos,12579.0,1334.536052,4001.395198,0.000000,78.000000,246.000000,923.000000,9.872900e+04
poblacion_2022,12579.0,89480.078862,166247.325112,413.000000,14092.000000,33951.000000,93464.000000,1.837168e+06
tasa_delitos_propiedad_100k,12579.0,1161.577339,1143.540686,0.000000,556.195623,940.929440,1522.381946,6.329114e+04
tasa_delitos_propiedad_pct,12579.0,1.161577,1.143541,0.000000,0.556196,0.940929,1.522382,6.329114e+01
variacion_acceso_internet_pct,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indice_IPC,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
variacion_anual_salarios_pct,4072.0,72.531758,48.832220,27.470000,32.990000,53.360000,145.470000,1.526800e+02
variacion_anual_cbt,4072.0,81.524047,61.428101,26.770000,40.470000,52.860000,106.620000,2.250800e+02
variacion_empleo_const_pct,4573.0,-0.964141,12.465468,-22.513076,-9.716127,2.804384,7.865122,1.625877e+01
mes,5074.0,12.000000,0.000000,12.000000,12.000000,12.000000,12.000000,1.200000e+01
variacion_anual_ipim,4573.0,79.892740,73.850793,18.850000,35.380000,58.490000,73.500000,2.763500e+02

Verificar por que no matchearon correctamente IPC y accesos internet

In [57]:
print(df_final["provincia_nombre"].unique())
print(variacion_accesos_internet_provincias_anual["jurisdiccion"].unique())

['ciudad autónoma de buenos aires' 'buenos aires' 'catamarca' 'córdoba'
 'corrientes' 'chaco' 'chubut' 'entre ríos' 'formosa' 'jujuy' 'la pampa'
 'la rioja' 'mendoza' 'misiones' 'neuquén' 'río negro' 'salta' 'san juan'
 'san luis' 'santa cruz' 'santa fe' 'santiago del estero' 'tucumán'
 'tierra del fuego, antártida e islas del atlántico sur']
['CABA y provincia de Buenos Aires' 'Catamarca' 'Chaco' 'Chubut'
 'Corrientes' 'Córdoba' 'Entre Ríos' 'Formosa' 'Jujuy' 'La Pampa'
 'La Rioja' 'Mendoza' 'Misiones' 'Neuquén' 'Río Negro' 'Salta' 'San Juan'
 'San Luis' 'Santa Cruz' 'Santa Fe' 'Santiago del Estero'
 'Tierra del Fuego, Antártida e Islas del Atlántico Sur' 'Total del país'
 'Tucumán']

In [58]:
print(df_final["region"].unique())
print(ipc["region"].unique())

['GBA' 'Pampeana' 'Noroeste' 'Noreste' 'Patagonia' 'Cuyo']
['cuyo' 'gba' 'nea' 'noa' 'pampeana' 'patagonia']

In [59]:
# Arreglar merge con variable de acceso a internet
df_internet = variacion_accesos_internet_provincias_anual.copy()

# Normalizar texto
df_internet["jurisdiccion"] = df_internet["jurisdiccion"].str.lower()

# Separar CABA + Buenos Aires
df_ba = df_internet[
    df_internet["jurisdiccion"] == "caba y provincia de buenos aires"
].copy()

df_ba_caba = df_ba.copy()
df_ba_caba["jurisdiccion"] = "ciudad autónoma de buenos aires"

df_ba_pba = df_ba.copy()
df_ba_pba["jurisdiccion"] = "buenos aires"

# Eliminar original y reemplazar
df_internet = df_internet[
    df_internet["jurisdiccion"] != "caba y provincia de buenos aires"
]

df_internet = pd.concat([df_internet, df_ba_caba, df_ba_pba], ignore_index=True)

In [60]:
# Rehacer el merge
df_final = df_final.drop(columns=["variacion_acceso_internet_pct"], errors="ignore")

df_final = df_final.merge(
    df_internet,
    left_on=["provincia_nombre", "anio"],
    right_on=["jurisdiccion", "anio"],
    how="left"
)

In [61]:
# Arreglar variable IPC (reemplazar regiones por provincias para hacer merge correcto)
map_region = {
    "gba": "GBA",
    "pampeana": "Pampeana",
    "cuyo": "Cuyo",
    "nea": "Noreste",
    "noa": "Noroeste",
    "patagonia": "Patagonia"
}

# Aplicar mapeo a la columna de región en el dataset de IPC
ipc["region"] = ipc["region"].str.lower().map(map_region)

In [62]:
# Rehacer merge
df_final = df_final.drop(columns=["Indice_IPC"], errors="ignore")

df_final = df_final.merge(
    ipc,
    on=["region", "anio"],
    how="left"
)

In [64]:
# Validar
df_final.isna().sum().sort_values(ascending=False)

variacion_acceso_internet_pct    8507
variacion_anual_cbt              8507
variacion_anual_salarios_pct     8507
Indice_IPC                       8006
variacion_anual_ipim             8006
variacion_empleo_const_pct       8006
jurisdiccion                     8006
mes                              7505
provincia_nombre                    0
provincia_id                        0
region                              0
tasa_delitos_propiedad_pct          0
tasa_delitos_propiedad_100k         0
poblacion_2022                      0
delitos_propiedad_hechos            0
anio                                0
departamento_nombre                 0
departamento_id                     0
dtype: int64

In [65]:
df_final.groupby("anio").size()

anio
2000    500
2001    500
2002    500
2003    500
2004    500
2005    500
2006    500
2007    500
2008    500
2009    500
2010    501
2011    501
2012    501
2013    501
2014    501
2015    501
2016    501
2017    501
2018    501
2019    501
2020    501
2021    501
2022    522
2023    523
2024    522
dtype: int64

In [66]:
# Filtro dataset desde año 2017 en adelante (porque antes hay muchos datos faltantes en las variables macro)
df_modelo = df_final[df_final["anio"] >= 2017].copy()
print(df_modelo.shape)
df_modelo.isna().sum().sort_values(ascending=False)

(4072, 18)

provincia_id                     0
provincia_nombre                 0
departamento_id                  0
departamento_nombre              0
anio                             0
delitos_propiedad_hechos         0
poblacion_2022                   0
tasa_delitos_propiedad_100k      0
tasa_delitos_propiedad_pct       0
region                           0
variacion_anual_salarios_pct     0
variacion_anual_cbt              0
variacion_empleo_const_pct       0
mes                              0
variacion_anual_ipim             0
jurisdiccion                     0
variacion_acceso_internet_pct    0
Indice_IPC                       0
dtype: int64

In [67]:
# Elimino columnas auxiliares innecesarias con datos faltantes
df_modelo = df_modelo.drop(columns=["jurisdiccion_y", "jurisdiccion_x","variacion_acceso_internet_pct_y", "variacion_acceso_internet_pct_x"], errors="ignore")
print(df_modelo.shape)
df_modelo.isna().sum().sort_values(ascending=False)

(4072, 18)

provincia_id                     0
provincia_nombre                 0
departamento_id                  0
departamento_nombre              0
anio                             0
delitos_propiedad_hechos         0
poblacion_2022                   0
tasa_delitos_propiedad_100k      0
tasa_delitos_propiedad_pct       0
region                           0
variacion_anual_salarios_pct     0
variacion_anual_cbt              0
variacion_empleo_const_pct       0
mes                              0
variacion_anual_ipim             0
jurisdiccion                     0
variacion_acceso_internet_pct    0
Indice_IPC                       0
dtype: int64

In [68]:
# Guardar dataset final para modelado
df_modelo.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/final/df_modelo.csv", index=False)
df_modelo.shape

(4072, 18)

In [69]:
# Creo un dataset copia del dataset final, solo del año 2024

df_mapa_2024 = df_modelo [df_modelo["anio"] == 2024].copy()

df_mapa_2024 = df_mapa_2024[[
    "provincia_id",
    "provincia_nombre",
    "departamento_id",
    "departamento_nombre",
    "anio",
    "delitos_propiedad_hechos",
    "tasa_delitos_propiedad_100k",
    "tasa_delitos_propiedad_pct"
]].copy()

In [70]:
# Guardo dataset
df_mapa_2024.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/final/dataset_mapa_2024.csv", index=False)

 # Dataset proyecciones de poblacion por año + datos superficie departamento

In [71]:


path_pob = r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/Proyecciones_departamento_2010-2025.csv"

df_proy_pob = pd.read_csv(path_pob)
df_proy_pob.head()

,Código de provincia,Provincia,Código de departamento,Departamento,Año 2010,Año 2011,Año 2012,Año 2013,Año 2014,Año 2015,...,Código de provincia.1,Nombre de provincia,Código de departamento.1,Nombre de departamento,Población total,Total de hogares,Latitud del centroide,Longitud del centroide,Superficie en km2,Geometría en GeoJSON
0,2,CABA,2001,Comuna 1,243946,245308,246689,248069,249433,250770,...,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,205886,84468,-34.606365,-58.371709,17.774344,"{""type"":""Polygon"",""coordinates"":[[[-58.386301,..."
1,2,CABA,2002,Comuna 2,150714,150573,150428,150278,150130,149985,...,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,157932,73156,-34.585876,-58.394997,6.276148,"{""type"":""Polygon"",""coordinates"":[[[-58.381109,..."
2,2,CABA,2003,Comuna 3,191323,191536,191750,191963,192171,192375,...,2,Ciudad Autónoma de Buenos Aires,2003,Comuna 3,187537,80489,-34.613826,-58.402686,6.386040,"{""type"":""Polygon"",""coordinates"":[[[-58.411917,..."
3,2,CABA,2004,Comuna 4,234933,235497,236071,236646,237214,237769,...,2,Ciudad Autónoma de Buenos Aires,2004,Comuna 4,218245,76455,-34.642292,-58.388860,21.694410,"{""type"":""MultiPolygon"",""coordinates"":[[[[-58.3..."
4,2,CABA,2005,Comuna 5,185301,185544,185789,186034,186276,186512,...,2,Ciudad Autónoma de Buenos Aires,2005,Comuna 5,179005,76846,-34.617353,-58.420607,6.659799,"{""type"":""Polygon"",""coordinates"":[[[-58.417264,..."

In [72]:
df_proy_pob.columns.tolist()

['Código de provincia',
 'Provincia',
 'Código de departamento',
 'Departamento',
 'Año 2010',
 'Año 2011',
 'Año 2012',
 'Año 2013',
 'Año 2014',
 'Año 2015',
 'Año 2016',
 'Año 2017',
 'Año 2018',
 'Año 2019',
 'Año 2020',
 'Año 2021',
 'Año 2022',
 'Año 2023',
 'Año 2024',
 'Año 2025',
 'Código de provincia.1',
 'Nombre de provincia',
 'Código de departamento.1',
 'Nombre de departamento',
 'Población total',
 'Total de hogares',
 'Latitud del centroide',
 'Longitud del centroide',
 'Superficie en km2',
 'Geometría en GeoJSON']

In [73]:
# Pasar dataset a formato largo
# 1. Identificar columnas de años
cols_anios = [col for col in df_proy_pob.columns if "Año" in col]

# 2. Pasar a formato largo
df_pob_long = df_proy_pob.melt(
    id_vars=[
        "Provincia",
        "Departamento",
        "Código de provincia",
        "Código de departamento",
        "Superficie en km2"
    ],
    value_vars=cols_anios,
    var_name="anio",
    value_name="poblacion"
)

# 3. Limpiar columna año
df_pob_long["anio"] = df_pob_long["anio"].str.replace("Año ", "").astype(int)

# 4. Ver resultado
df_pob_long.head()

,Provincia,Departamento,Código de provincia,Código de departamento,Superficie en km2,anio,poblacion
0,CABA,Comuna 1,2,2001,17.774344,2010,243946.0
1,CABA,Comuna 2,2,2002,6.276148,2010,150714.0
2,CABA,Comuna 3,2,2003,6.386040,2010,191323.0
3,CABA,Comuna 4,2,2004,21.694410,2010,234933.0
4,CABA,Comuna 5,2,2005,6.659799,2010,185301.0

In [74]:
df_pob_long.tail()

,Provincia,Departamento,Código de provincia,Código de departamento,Superficie en km2,anio,poblacion
8395,Tucumán,Tafí Viejo,90,90105,1139.078712,2025,162025.0
8396,Tucumán,Trancas,90,90112,3068.140292,2025,23033.0
8397,Tucumán,Yerba Buena,90,90119,149.164148,2025,105914.0
8398,Tierra del Fuego,Río Grande,94,94007,11767.490783,2025,107928.0
8399,Tierra del Fuego,Ushuaia,94,94014,8910.185239,2025,86678.0

In [75]:
# Cargar df_mapa_final
df_mapa_final = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/final/dataset_mapa_final.csv")
df_mapa_final.shape

(4072, 20)

In [77]:
import unicodedata
import re

def normalizar_texto(s):
    if pd.isna(s):
        return s
    s = str(s).strip().lower()
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("utf-8")
    s = re.sub(r"\s+", " ", s)
    return s

df_pob_long["provincia_key"] = df_pob_long["Provincia"].apply(normalizar_texto)
df_pob_long["departamento_key"] = df_pob_long["Departamento"].apply(normalizar_texto)

df_mapa_final["provincia_key"] = df_mapa_final["provincia_nombre"].apply(normalizar_texto)
df_mapa_final["departamento_key"] = df_mapa_final["departamento_nombre"].apply(normalizar_texto)

df_mapa_final.columns.tolist()

['provincia_id',
 'provincia_nombre',
 'departamento_id',
 'departamento_nombre',
 'anio',
 'delitos_propiedad_hechos',
 'poblacion_2022',
 'tasa_delitos_propiedad_100k',
 'tasa_delitos_propiedad_pct',
 'region',
 'variacion_anual_salarios_pct',
 'variacion_anual_cbt',
 'variacion_empleo_const_pct',
 'mes',
 'variacion_anual_ipim',
 'jurisdiccion',
 'variacion_acceso_internet_pct',
 'Indice_IPC',
 'lat',
 'lon',
 'provincia_key',
 'departamento_key']

In [78]:
# Merge
df_mapa_sup_final = df_mapa_final.merge(
    df_pob_long[[
        "provincia_key",
        "departamento_key",
        "anio",
        "poblacion",
        "Superficie en km2"
    ]],
    on=["provincia_key", "departamento_key", "anio"],
    how="left"
)

In [79]:
df_mapa_sup_final[["provincia_nombre", "departamento_nombre", "anio", "poblacion", "Superficie en km2"]].head()

,provincia_nombre,departamento_nombre,anio,poblacion,Superficie en km2
0,ciudad autónoma de buenos aires,comuna 1,2017,NaN,NaN
1,ciudad autónoma de buenos aires,comuna 1,2018,NaN,NaN
2,ciudad autónoma de buenos aires,comuna 1,2019,NaN,NaN
3,ciudad autónoma de buenos aires,comuna 1,2020,NaN,NaN
4,ciudad autónoma de buenos aires,comuna 1,2021,NaN,NaN

In [80]:
# Ver ejemplos de claves en ambos datasets

print("df_mapa_final:")
print(df_mapa_final[["provincia_nombre", "departamento_nombre", "provincia_key", "departamento_key"]].drop_duplicates().head(10))

print("\ndf_pob_long:")
print(df_pob_long[["Provincia", "Departamento", "provincia_key", "departamento_key"]].drop_duplicates().head(10))

df_mapa_final:
                   provincia_nombre departamento_nombre  \
0   ciudad autónoma de buenos aires            comuna 1
8   ciudad autónoma de buenos aires            comuna 2
16  ciudad autónoma de buenos aires            comuna 3
24  ciudad autónoma de buenos aires            comuna 4
32  ciudad autónoma de buenos aires            comuna 5
40  ciudad autónoma de buenos aires            comuna 6
48  ciudad autónoma de buenos aires            comuna 7
56  ciudad autónoma de buenos aires            comuna 8
64  ciudad autónoma de buenos aires            comuna 9
72  ciudad autónoma de buenos aires           comuna 10

                      provincia_key departamento_key
0   ciudad autonoma de buenos aires         comuna 1
8   ciudad autonoma de buenos aires         comuna 2
16  ciudad autonoma de buenos aires         comuna 3
24  ciudad autonoma de buenos aires         comuna 4
32  ciudad autonoma de buenos aires         comuna 5
40  ciudad autonoma de buenos aires         comuna 6
48  ciudad autonoma de buenos aires         comuna 7
56  ciudad autonoma de buenos aires         comuna 8
64  ciudad autonoma de buenos aires         comuna 9
72  ciudad autonoma de buenos aires        comuna 10

df_pob_long:
  Provincia Departamento provincia_key departamento_key
0      CABA     Comuna 1          caba         comuna 1
1      CABA     Comuna 2          caba         comuna 2
2      CABA     Comuna 3          caba         comuna 3
3      CABA     Comuna 4          caba         comuna 4
4      CABA     Comuna 5          caba         comuna 5
5      CABA     Comuna 6          caba         comuna 6
6      CABA     Comuna 7          caba         comuna 7
7      CABA     Comuna 8          caba         comuna 8
8      CABA     Comuna 9          caba         comuna 9
9      CABA    Comuna 10          caba        comuna 10

In [81]:
# Normalizar provincia en df_pob_long
df_pob_long["provincia_key"] = df_pob_long["provincia_key"].replace({
    "caba": "ciudad autonoma de buenos aires"
})

In [82]:
df_mapa_sup_final = df_mapa_final.merge(
    df_pob_long[[
        "provincia_key",
        "departamento_key",
        "anio",
        "poblacion",
        "Superficie en km2"
    ]],
    on=["provincia_key", "departamento_key", "anio"],
    how="left",
    indicator=True
)

df_mapa_sup_final["_merge"].value_counts()

_merge
both          3979
left_only       93
right_only       0
Name: count, dtype: int64

In [83]:
faltantes_merge = df_mapa_sup_final.loc[
    df_mapa_sup_final["_merge"] == "left_only",
    ["provincia_nombre", "departamento_nombre", "anio", "provincia_key", "departamento_key"]
].drop_duplicates().sort_values(["provincia_nombre", "departamento_nombre", "anio"])

faltantes_merge.head(50)

,provincia_nombre,departamento_nombre,anio,provincia_key,departamento_key
322,buenos aires,coronel de marina l. rosales,2017,buenos aires,coronel de marina l. rosales
323,buenos aires,coronel de marina l. rosales,2018,buenos aires,coronel de marina l. rosales
324,buenos aires,coronel de marina l. rosales,2019,buenos aires,coronel de marina l. rosales
325,buenos aires,coronel de marina l. rosales,2020,buenos aires,coronel de marina l. rosales
326,buenos aires,coronel de marina l. rosales,2021,buenos aires,coronel de marina l. rosales
327,buenos aires,coronel de marina l. rosales,2022,buenos aires,coronel de marina l. rosales
328,buenos aires,coronel de marina l. rosales,2023,buenos aires,coronel de marina l. rosales
329,buenos aires,coronel de marina l. rosales,2024,buenos aires,coronel de marina l. rosales
682,buenos aires,lezama,2017,buenos aires,lezama
683,buenos aires,lezama,2018,buenos aires,lezama
684,buenos aires,lezama,2019,buenos aires,lezama
685,buenos aires,lezama,2020,buenos aires,lezama
686,buenos aires,lezama,2021,buenos aires,lezama
687,buenos aires,lezama,2022,buenos aires,lezama
688,buenos aires,lezama,2023,buenos aires,lezama
689,buenos aires,lezama,2024,buenos aires,lezama
1864,chaco,o' higgins,2017,chaco,o' higgins
1865,chaco,o' higgins,2018,chaco,o' higgins
1866,chaco,o' higgins,2019,chaco,o' higgins
1867,chaco,o' higgins,2020,chaco,o' higgins
1868,chaco,o' higgins,2021,chaco,o' higgins
1869,chaco,o' higgins,2022,chaco,o' higgins
1870,chaco,o' higgins,2023,chaco,o' higgins
1871,chaco,o' higgins,2024,chaco,o' higgins
1872,chaco,presidencia de la plaza,2017,chaco,presidencia de la plaza
1873,chaco,presidencia de la plaza,2018,chaco,presidencia de la plaza
1874,chaco,presidencia de la plaza,2019,chaco,presidencia de la plaza
1875,chaco,presidencia de la plaza,2020,chaco,presidencia de la plaza
1876,chaco,presidencia de la plaza,2021,chaco,presidencia de la plaza
1877,chaco,presidencia de la plaza,2022,chaco,presidencia de la plaza
1878,chaco,presidencia de la plaza,2023,chaco,presidencia de la plaza
1879,chaco,presidencia de la plaza,2024,chaco,presidencia de la plaza
1336,córdoba,cordoba capital,2017,cordoba,cordoba capital
1337,córdoba,cordoba capital,2018,cordoba,cordoba capital
1338,córdoba,cordoba capital,2019,cordoba,cordoba capital
1339,córdoba,cordoba capital,2020,cordoba,cordoba capital
1340,córdoba,cordoba capital,2021,cordoba,cordoba capital
1341,córdoba,cordoba capital,2022,cordoba,cordoba capital
1342,córdoba,cordoba capital,2023,cordoba,cordoba capital
1343,córdoba,cordoba capital,2024,cordoba,cordoba capital
2415,la pampa,chicalcó,2023,la pampa,chicalco
2416,la pampa,chicalcó,2024,la pampa,chicalco
2438,la pampa,quemú ouemú,2022,la pampa,quemu ouemu
2439,la pampa,quemú ouemú,2023,la pampa,quemu ouemu
2440,la pampa,quemú ouemú,2024,la pampa,quemu ouemu
2584,mendoza,mendoza capital,2017,mendoza,mendoza capital
2585,mendoza,mendoza capital,2018,mendoza,mendoza capital
2586,mendoza,mendoza capital,2019,mendoza,mendoza capital
2587,mendoza,mendoza capital,2020,mendoza,mendoza capital
2588,mendoza,mendoza capital,2021,mendoza,mendoza capital

In [84]:
faltantes_merge[["provincia_nombre", "departamento_nombre"]].drop_duplicates().sort_values(
    ["provincia_nombre", "departamento_nombre"]
)

,provincia_nombre,departamento_nombre
322,buenos aires,coronel de marina l. rosales
682,buenos aires,lezama
1864,chaco,o' higgins
1872,chaco,presidencia de la plaza
1336,córdoba,cordoba capital
2415,la pampa,chicalcó
2438,la pampa,quemú ouemú
2584,mendoza,mendoza capital
2808,misiones,libertador grl. san martín
3152,salta,grl. josé de san martín
4056,"tierra del fuego, antártida e islas del atlánt...",río grande
4064,"tierra del fuego, antártida e islas del atlánt...",ushuaia
3960,tucumán,juan bautista alberdi

In [85]:
# Correcciones manuales de nombres para mejorar el match
reemplazos_provincias_mapa = {
    "tierra del fuego, antartida e islas del atlantico sur": "tierra del fuego"
}

df_mapa_final["provincia_key"] = df_mapa_final["provincia_key"].replace(reemplazos_provincias_mapa)

In [86]:
# Mergear nuevamente
df_mapa_sup_final = df_mapa_final.merge(
    df_pob_long[[
        "provincia_key",
        "departamento_key",
        "anio",
        "poblacion",
        "Superficie en km2"
    ]],
    on=["provincia_key", "departamento_key", "anio"],
    how="left",
    indicator=True
)

df_mapa_sup_final["_merge"].value_counts()

_merge
both          3995
left_only       77
right_only       0
Name: count, dtype: int64

In [87]:
# Verificar nuevamente los merge faltantes
faltantes_merge = df_mapa_sup_final.loc[
    df_mapa_sup_final["_merge"] == "left_only",
    ["provincia_nombre", "departamento_nombre", "anio", "provincia_key", "departamento_key"]
].drop_duplicates().sort_values(["provincia_nombre", "departamento_nombre", "anio"])

faltantes_merge[["provincia_nombre", "departamento_nombre"]].drop_duplicates().sort_values(
    ["provincia_nombre", "departamento_nombre"]
)

     provincia_nombre           departamento_nombre
322      buenos aires  coronel de marina l. rosales
682      buenos aires                        lezama
1864            chaco                    o' higgins
1872            chaco       presidencia de la plaza
1336          córdoba               cordoba capital
2415         la pampa                      chicalcó
2438         la pampa                   quemú ouemú
2584          mendoza               mendoza capital
2808         misiones    libertador grl. san martín
3152            salta       grl. josé de san martín
3960          tucumán         juan bautista alberdi

In [88]:
faltantes = df_mapa_sup_final[df_mapa_sup_final["_merge"] == "left_only"]

faltantes.head(50)

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,poblacion_2022,tasa_delitos_propiedad_100k,tasa_delitos_propiedad_pct,region,...,jurisdiccion,variacion_acceso_internet_pct,Indice_IPC,lat,lon,provincia_key,departamento_key,poblacion,Superficie en km2,_merge
322,6,buenos aires,6182,coronel de marina l. rosales,2017,259,65823,393.479483,0.393479,Pampeana,...,buenos aires,4.281205,112.744967,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
323,6,buenos aires,6182,coronel de marina l. rosales,2018,443,65823,673.017031,0.673017,Pampeana,...,buenos aires,-0.084572,151.744600,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
324,6,buenos aires,6182,coronel de marina l. rosales,2019,733,65823,1113.592513,1.113593,Pampeana,...,buenos aires,3.259377,232.926758,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
325,6,buenos aires,6182,coronel de marina l. rosales,2020,716,65823,1087.765675,1.087766,Pampeana,...,buenos aires,-0.906055,333.645717,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
326,6,buenos aires,6182,coronel de marina l. rosales,2021,726,65823,1102.957933,1.102958,Pampeana,...,buenos aires,5.042552,499.073575,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
327,6,buenos aires,6182,coronel de marina l. rosales,2022,875,65823,1329.322577,1.329323,Pampeana,...,buenos aires,9.714659,855.284483,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
328,6,buenos aires,6182,coronel de marina l. rosales,2023,1135,65823,1724.321286,1.724321,Pampeana,...,buenos aires,7.971208,1996.292658,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
329,6,buenos aires,6182,coronel de marina l. rosales,2024,913,65823,1387.053158,1.387053,Pampeana,...,buenos aires,2.207989,6356.215883,-38.849077,-61.835584,buenos aires,coronel de marina l. rosales,NaN,NaN,left_only
682,6,buenos aires,6466,lezama,2017,33,6170,534.846029,0.534846,Pampeana,...,buenos aires,4.281205,112.744967,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
683,6,buenos aires,6466,lezama,2018,43,6170,696.920583,0.696921,Pampeana,...,buenos aires,-0.084572,151.744600,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
684,6,buenos aires,6466,lezama,2019,59,6170,956.239870,0.956240,Pampeana,...,buenos aires,3.259377,232.926758,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
685,6,buenos aires,6466,lezama,2020,29,6170,470.016207,0.470016,Pampeana,...,buenos aires,-0.906055,333.645717,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
686,6,buenos aires,6466,lezama,2021,29,6170,470.016207,0.470016,Pampeana,...,buenos aires,5.042552,499.073575,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
687,6,buenos aires,6466,lezama,2022,29,6170,470.016207,0.470016,Pampeana,...,buenos aires,9.714659,855.284483,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
688,6,buenos aires,6466,lezama,2023,55,6170,891.410049,0.891410,Pampeana,...,buenos aires,7.971208,1996.292658,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
689,6,buenos aires,6466,lezama,2024,81,6170,1312.803890,1.312804,Pampeana,...,buenos aires,2.207989,6356.215883,-35.849208,-57.894844,buenos aires,lezama,NaN,NaN,left_only
1336,14,córdoba,14014,cordoba capital,2017,71061,1498060,4743.534972,4.743535,Pampeana,...,córdoba,5.569432,112.744967,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1337,14,córdoba,14014,cordoba capital,2018,72358,1498060,4830.113614,4.830114,Pampeana,...,córdoba,0.537924,151.744600,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1338,14,córdoba,14014,cordoba capital,2019,78403,1498060,5233.635502,5.233636,Pampeana,...,córdoba,-0.064106,232.926758,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1339,14,córdoba,14014,cordoba capital,2020,50187,1498060,3350.132838,3.350133,Pampeana,...,córdoba,2.329265,333.645717,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1340,14,córdoba,14014,cordoba capital,2021,57174,1498060,3816.536053,3.816536,Pampeana,...,córdoba,5.163608,499.073575,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1341,14,córdoba,14014,cordoba capital,2022,68878,1498060,4597.813172,4.597813,Pampeana,...,córdoba,6.372812,855.284483,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1342,14,córdoba,14014,cordoba capital,2023,98729,1498060,6590.456991,6.590457,Pampeana,...,córdoba,6.382301,1996.292658,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1343,14,córdoba,14014,cordoba capital,2024,91725,1498060,6122.918975,6.122919,Pampeana,...,córdoba,1.561889,6356.215883,-31.416757,-64.183584,cordoba,cordoba capital,NaN,NaN,left_only
1864,22,chaco,22112,o' higgins,2017,180,21544,835.499443,0.835499,Noreste,...,chaco,15.913362,112.161883,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1865,22,chaco,22112,o' higgins,2018,229,21544,1062.940958,1.062941,Noreste,...,chaco,1.605305,148.771275,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1866,22,chaco,22112,o' higgins,2019,159,21544,738.024508,0.738025,Noreste,...,chaco,1.276343,232.355408,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1867,22,chaco,22112,o' higgins,2020,145,21544,673.041218,0.673041,Noreste,...,chaco,1.741870,339.326200,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1868,22,chaco,22112,o' higgins,2021,226,21544,1049.015967,1.049016,Noreste,...,chaco,8.033069,509.507950,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1869,22,chaco,22112,o' higgins,2022,155,21544,719.457854,0.719458,Noreste,...,chaco,12.580005,885.369425,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1870,22,chaco,22112,o' higgins,2023,169,21544,784.441144,0.784441,Noreste,...,chaco,10.050678,2076.622467,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1871,22,chaco,22112,o' higgins,2024,207,21544,960.824359,0.960824,Noreste,...,chaco,2.710916,6418.266283,-27.255654,-60.679975,chaco,o' higgins,NaN,NaN,left_only
1872,22,chaco,22119,presidencia de la plaza,2017,79,13938,566.795810,0.566796,Noreste,...,chaco,15.913362,112.161883,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
1873,22,chaco,22119,presidencia de la plaza,2018,98,13938,703.113790,0.703114,Noreste,...,chaco,1.605305,148.771275,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
1874,22,chaco,22119,presidencia de la plaza,2019,89,13938,638.542115,0.638542,Noreste,...,chaco,1.276343,232.355408,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
1875,22,chaco,22119,presidencia de la plaza,2020,77,13938,552.446549,0.552447,Noreste,...,chaco,1.741870,339.326200,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
1876,22,chaco,22119,presidencia de la plaza,2021,73,13938,523.748027,0.523748,Noreste,...,chaco,8.033069,509.507950,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
1877,22,chaco,22119,presidencia de la plaza,2022,89,13938,638.542115,0.638542,Noreste,...,chaco,12.580005,885.369425,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
1878,22,chaco,22119,presidencia de la plaza,2023,101,13938,724.637681,0.724638,Noreste,...,chaco,10.050678,2076.622467,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
1879,22,chaco,22119,presidencia de la plaza,2024,130,13938,932.701966,0.932702,Noreste,...,chaco,2.710916,6418.266283,-27.044625,-59.774564,chaco,presidencia de la plaza,NaN,NaN,left_only
2415,42,la pampa,42063,chicalcó,2023,1,1461,68.446270,0.068446,Pampeana,...,la pampa,6.396252,1996.292658,-36.396974,-67.694467,la pampa,chicalco,NaN,NaN,left_only
2416,42,la pampa,42063,chicalcó,2024,4,1461,273.785079,0.273785,Pampeana,...,la pampa,2.936667,6356.215883,-36.396974,-67.694467,la pampa,chicalco,NaN,NaN,left_only
2438,42,la pampa,42119,quemú ouemú,2022,3,8404,35.697287,0.035697,Pampeana,...,la pampa,6.152194,855.284483,-36.130641,-63.663730,la pampa,quemu ouemu,NaN,NaN,left_only
2439,42,la pampa,42119,quemú ouemú,2023,31,8404,368.871966,0.368872,Pampeana,...,la pampa,6.396252,1996.292658,-36.130641,-63.663730,la pampa,quemu ouemu,NaN,NaN,left_only
2440,42,la pampa,42119,quemú ouemú,2024,66,8404,785.340314,0.785340,Pampeana,...,la pampa,2.936667,6356.215883,-36.130641,-63.663730,la pampa,quemu ouemu,NaN,NaN,left_only
2584,50,mendoza,50007,mendoza capital,2017,8893,123715,7188.295680,7.188296,Cuyo,...,mendoza,2.638317,113.153533,-32.882896,-68.893649,mendoza,mendoza capital,NaN,NaN,left_only
2585,50,mendoza,50007,mendoza capital,2018,7555,123715,6106.777674,6.106778,Cuyo,...,mendoza,-4.557891,153.102808,-32.882896,-68.893649,mendoza,mendoza capital,NaN,NaN,left_only
2586,50,mendoza,50007,mendoza capital,2019,7814,123715,6316.129814,6.316130,Cuyo,...,mendoza,-0.984566,237.596583,-32.882896,-68.893649,mendoza,mendoza capital,NaN,NaN,left_only
2587,50,mendoza,50007,mendoza capital,2020,5769,123715,4663.137049,4.663137,Cuyo,...,mendoza,8.475171,340.498000,-32.882896,-68.893649,mendoza,mendoza capital,NaN,NaN,left_only
2588,50,mendoza,50007,mendoza capital,2021,9025,123715,7294.992523,7.294993,Cuyo,...,mendoza,5.750420,510.842458,-32.882896,-68.893649,mendoza,mendoza capital,NaN,NaN,left_only

In [89]:
# Buscar en df_pob_long coincidencias de nombres de los departamentos faltantes
# Buscar aproximaciones más amplias
busquedas = [
    "rosales",
    "lezama",
    "higgins",
    "plaza",
    "chical",
    "alberdi",
    "capital",
    "san mart",
    "quemu"
]

print("df_pob_long:")
for b in busquedas:
    print(f"\n--- Buscando: {b} ---")
    display(
        df_pob_long[
            df_pob_long["departamento_key"].str.contains(b, na=False)
        ][["Provincia", "Departamento", "provincia_key", "departamento_key"]].drop_duplicates()
    )

print("df_mapa_final:")
for b in busquedas:
    print(f"\n--- Buscando: {b} ---")
    display(
        df_mapa_final[
            df_mapa_final["departamento_key"].str.contains(b, na=False)
        ][["provincia_nombre", "departamento_nombre", "provincia_key", "departamento_key"]].drop_duplicates()
    )

df_pob_long:

--- Buscando: rosales ---

,Provincia,Departamento,provincia_key,departamento_key
45,Buenos Aires,Coronel Leonardo Rosales,buenos aires,coronel leonardo rosales

--- Buscando: lezama ---

Empty DataFrame
Columns: [Provincia, Departamento, provincia_key, departamento_key]
Index: []

--- Buscando: higgins ---

    Provincia Departamento provincia_key departamento_key
232     Chaco    O'Higgins         chaco        o'higgins

--- Buscando: plaza ---

    Provincia            Departamento provincia_key        departamento_key
233     Chaco  Presidente de la Plaza         chaco  presidente de la plaza

--- Buscando: chical ---

    Provincia Departamento provincia_key departamento_key
304  La Pampa    Chical Co      la pampa        chical co

--- Buscando: alberdi ---

,Provincia,Departamento,provincia_key,departamento_key
480,Santiago del Estero,Alberdi,santiago del estero,alberdi
512,Tucumán,Juan B. Alberdi,tucuman,juan b. alberdi

--- Buscando: capital ---

               Provincia Departamento        provincia_key departamento_key
155            Catamarca      Capital            catamarca          capital
166              Córdoba      Capital              cordoba          capital
193           Corrientes      Capital           corrientes          capital
300             La Pampa      Capital             la pampa          capital
321             La Rioja      Capital             la rioja          capital
338              Mendoza      Capital              mendoza          capital
359             Misiones      Capital             misiones          capital
405                Salta      Capital                salta          capital
428             San Juan      Capital             san juan          capital
451             San Luis   La Capital             san luis       la capital
468             Santa Fe   La Capital             santa fe       la capital
485  Santiago del Estero      Capital  santiago del estero          capital
507              Tucumán      Capital              tucuman          capital

--- Buscando: san mart ---

,Provincia,Departamento,provincia_key,departamento_key
71,Buenos Aires,General San Martín,buenos aires,general san martin
170,Córdoba,General San Martín,cordoba,general san martin
211,Corrientes,San Martín,corrientes,san martin
228,Chaco,Libertador General San Martín,chaco,libertador general san martin
332,La Rioja,General San Martín,la rioja,general san martin
351,Mendoza,San Martín,mendoza,san martin
366,Misiones,Libertador General San Martín,misiones,libertador general san martin
409,Salta,General José de San Martín,salta,general jose de san martin
437,San Juan,San Martín,san juan,san martin
452,San Luis,Libertador General San Martín,san luis,libertador general san martin
477,Santa Fe,San Martín,santa fe,san martin
503,Santiago del Estero,San Martín,santiago del estero,san martin

--- Buscando: quemu ---

    Provincia Departamento provincia_key departamento_key
314  La Pampa  Quemú Quemú      la pampa      quemu quemu

df_mapa_final:

--- Buscando: rosales ---

,provincia_nombre,departamento_nombre,provincia_key,departamento_key
322,buenos aires,coronel de marina l. rosales,buenos aires,coronel de marina l. rosales

--- Buscando: lezama ---

    provincia_nombre departamento_nombre provincia_key departamento_key
682     buenos aires              lezama  buenos aires           lezama

--- Buscando: higgins ---

     provincia_nombre departamento_nombre provincia_key departamento_key
1864            chaco          o' higgins         chaco       o' higgins

--- Buscando: plaza ---

,provincia_nombre,departamento_nombre,provincia_key,departamento_key
1872,chaco,presidencia de la plaza,chaco,presidencia de la plaza

--- Buscando: chical ---

     provincia_nombre departamento_nombre provincia_key departamento_key
2415         la pampa            chicalcó      la pampa         chicalco

--- Buscando: alberdi ---

,provincia_nombre,departamento_nombre,provincia_key,departamento_key
3712,santiago del estero,alberdi,santiago del estero,alberdi
3960,tucumán,juan bautista alberdi,tucuman,juan bautista alberdi

--- Buscando: capital ---

,provincia_nombre,departamento_nombre,provincia_key,departamento_key
1248,catamarca,capital,catamarca,capital
1336,córdoba,cordoba capital,cordoba,cordoba capital
1552,corrientes,capital,corrientes,capital
2397,la pampa,capital,la pampa,capital
2464,la rioja,capital,la rioja,capital
2584,mendoza,mendoza capital,mendoza,mendoza capital
2752,misiones,capital,misiones,capital
3120,salta,capital,salta,capital
3304,san juan,capital,san juan,capital
3616,santa fe,la capital,santa fe,la capital
3752,santiago del estero,capital,santiago del estero,capital
4008,tucumán,capital,tucuman,capital

--- Buscando: san mart ---

,provincia_nombre,departamento_nombre,provincia_key,departamento_key
554,buenos aires,general san martín,buenos aires,general san martin
1368,córdoba,general san martín,cordoba,general san martin
1696,corrientes,san martín,corrientes,san martin
1832,chaco,libertador general san martín,chaco,libertador general san martin
2536,la rioja,general san martín,la rioja,general san martin
2688,mendoza,san martín,mendoza,san martin
2808,misiones,libertador grl. san martín,misiones,libertador grl. san martin
3152,salta,grl. josé de san martín,salta,grl. jose de san martin
3376,san juan,san martín,san juan,san martin
3488,san luis,libertador general san martín,san luis,libertador general san martin
3688,santa fe,san martín,santa fe,san martin
3896,santiago del estero,san martín,santiago del estero,san martin

--- Buscando: quemu ---

     provincia_nombre departamento_nombre provincia_key departamento_key
2438         la pampa         quemú ouemú      la pampa      quemu ouemu

In [90]:
df_pob_long[
    df_pob_long["Departamento"].str.contains("Lezama", case=False, na=False)
][["Provincia", "Departamento", "departamento_key"]].drop_duplicates()

Empty DataFrame
Columns: [Provincia, Departamento, departamento_key]
Index: []

In [91]:
print(
    df_pob_long[
        df_pob_long["provincia_key"] == "buenos aires"
    ][["Departamento", "departamento_key"]]
    .drop_duplicates()
    .sort_values("Departamento")
    .to_string(index=False)
)

            Departamento         departamento_key
              25 de Mayo               25 de mayo
              9 de Julio               9 de julio
           Adolfo Alsina            adolfo alsina
  Adolfo Gonzales Chaves   adolfo gonzales chaves
                 Alberti                  alberti
         Almirante Brown          almirante brown
               Arrecifes                arrecifes
              Avellaneda               avellaneda
                Ayacucho                 ayacucho
                    Azul                     azul
            Bahía Blanca             bahia blanca
                Balcarce                 balcarce
                Baradero                 baradero
           Benito Juárez            benito juarez
             Berazategui              berazategui
                 Berisso                  berisso
                 Bolívar                  bolivar
                 Bragado                  bragado
                Brandsen                 brandsen
                 Campana                  campana
       Capitán Sarmiento        capitan sarmiento
          Carlos Casares           carlos casares
          Carlos Tejedor           carlos tejedor
         Carmen de Areco          carmen de areco
                Castelli                 castelli
                Cañuelas                 canuelas
               Chacabuco                chacabuco
               Chascomús                chascomus
               Chivilcoy                chivilcoy
                   Colón                    colon
         Coronel Dorrego          coronel dorrego
Coronel Leonardo Rosales coronel leonardo rosales
        Coronel Pringles         coronel pringles
          Coronel Suárez           coronel suarez
                Daireaux                 daireaux
                 Dolores                  dolores
                Ensenada                 ensenada
                 Escobar                  escobar
      Esteban Echeverría       esteban echeverria
   Exaltación de la Cruz    exaltacion de la cruz
                  Ezeiza                   ezeiza
        Florencio Varela         florencio varela
     Florentino Ameghino      florentino ameghino
        General Alvarado         general alvarado
          General Alvear           general alvear
        General Arenales         general arenales
        General Belgrano         general belgrano
           General Guido            general guido
  General Juan Madariaga   general juan madariaga
       General La Madrid        general la madrid
       General Las Heras        general las heras
         General Lavalle          general lavalle
             General Paz              general paz
           General Pinto            general pinto
      General Pueyrredón       general pueyrredon
       General Rodríguez        general rodriguez
      General San Martín       general san martin
        General Viamonte         general viamonte
        General Villegas         general villegas
                 Guaminí                  guamini
       Hipólito Yrigoyen        hipolito yrigoyen
              Hurlingham               hurlingham
               Ituzaingó                ituzaingo
             José C. Paz              jose c. paz
                   Junín                    junin
                La Costa                 la costa
              La Matanza               la matanza
                La Plata                 la plata
                   Lanús                    lanus
                 Laprida                  laprida
              Las Flores               las flores
         Leandro N. Alem          leandro n. alem
                 Lincoln                  lincoln
                 Lobería                  loberia
                   Lobos                    lobos
         Lomas de Zamora          lomas de zamora
                   Luján                    lujan
               Magdalena                magdalena
                   Maipú                    maipu
     Malvinas Argentinas      malvinas argentinas
            Mar Chiquita             mar chiquita
              Marcos Paz               marcos paz
                Mercedes                 mercedes
                   Merlo                    merlo
                   Monte                    monte
           Monte Hermoso            monte hermoso
                  Moreno                   moreno
                   Morón                    moron
                 Navarro                  navarro
                Necochea                 necochea
               Olavarría                olavarria
               Patagones                patagones
                 Pehuajó                  pehuajo
              Pellegrini               pellegrini
               Pergamino                pergamino
                    Pila                     pila
                   Pilar                    pilar
                 Pinamar                  pinamar
        Presidente Perón         presidente peron
             Punta Indio              punta indio
                    Puán                     puan
                 Quilmes                  quilmes
                 Ramallo                  ramallo
                   Rauch                    rauch
               Rivadavia                rivadavia
                   Rojas                    rojas
             Roque Pérez              roque perez
                Saavedra                 saavedra
               Saladillo                saladillo
              Salliqueló               salliquelo
                   Salto                    salto
     San Andrés de Giles      san andres de giles
    San Antonio de Areco     san antonio de areco
            San Cayetano             san cayetano
            San Fernando             san fernando
              San Isidro               san isidro
              San Miguel               san miguel
             San Nicolás              san nicolas
               San Pedro                san pedro
             San Vicente              san vicente
                Suipacha                 suipacha
                  Tandil                   tandil
                Tapalqué                 tapalque
                   Tigre                    tigre
                Tordillo                 tordillo
               Tornquist                tornquist
         Trenque Lauquen          trenque lauquen
            Tres Arroyos             tres arroyos
              Tres Lomas               tres lomas
         Tres de Febrero          tres de febrero
           Vicente López            vicente lopez
            Villa Gesell             villa gesell
               Villarino                villarino
                  Zárate                   zarate

In [92]:
reemplazos_finales = {
    "coronel de marina l. rosales": "coronel leonardo rosales",
    "o' higgins": "o'higgins",
    "presidencia de la plaza": "presidente de la plaza",
    "chicalco": "chical co",
    "juan bautista alberdi": "juan b. alberdi",
    "cordoba capital":"capital",
    "mendoza capital":"capital",
    "libertador grl. san martin":"libertador general san martin",
    "grl. jose de san martin":"general jose de san martin",
    "quemu ouemu":"quemu quemu"
}

df_mapa_final["departamento_key"] = df_mapa_final["departamento_key"].replace(reemplazos_finales)

In [93]:
# De nuevo el merge...
df_mapa_sup_final = df_mapa_final.merge(
    df_pob_long[[
        "provincia_key",
        "departamento_key",
        "anio",
        "poblacion",
        "Superficie en km2"
    ]],
    on=["provincia_key", "departamento_key", "anio"],
    how="left",
    indicator=True
)

df_mapa_sup_final["_merge"].value_counts()

_merge
both          4064
left_only        8
right_only       0
Name: count, dtype: int64

In [94]:

print(df_mapa_sup_final.columns)
df_mapa_sup_final.head()

Index(['provincia_id', 'provincia_nombre', 'departamento_id',
       'departamento_nombre', 'anio', 'delitos_propiedad_hechos',
       'poblacion_2022', 'tasa_delitos_propiedad_100k',
       'tasa_delitos_propiedad_pct', 'region', 'variacion_anual_salarios_pct',
       'variacion_anual_cbt', 'variacion_empleo_const_pct', 'mes',
       'variacion_anual_ipim', 'jurisdiccion', 'variacion_acceso_internet_pct',
       'Indice_IPC', 'lat', 'lon', 'provincia_key', 'departamento_key',
       'poblacion', 'Superficie en km2', '_merge'],
      dtype='object')

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,poblacion_2022,tasa_delitos_propiedad_100k,tasa_delitos_propiedad_pct,region,...,jurisdiccion,variacion_acceso_internet_pct,Indice_IPC,lat,lon,provincia_key,departamento_key,poblacion,Superficie en km2,_merge
0,2,ciudad autónoma de buenos aires,2001,comuna 1,2017,17609,221001,7967.837250,7.967837,GBA,...,ciudad autónoma de buenos aires,4.281205,112.985075,-34.606444,-58.371512,ciudad autonoma de buenos aires,comuna 1,253271.0,17.774344,both
1,2,ciudad autónoma de buenos aires,2001,comuna 1,2018,18374,221001,8313.989529,8.313990,GBA,...,ciudad autónoma de buenos aires,-0.084572,151.569817,-34.606444,-58.371512,ciudad autonoma de buenos aires,comuna 1,254408.0,17.774344,both
2,2,ciudad autónoma de buenos aires,2001,comuna 1,2019,21721,221001,9828.462315,9.828462,GBA,...,ciudad autónoma de buenos aires,3.259377,231.605092,-34.606444,-58.371512,ciudad autonoma de buenos aires,comuna 1,255457.0,17.774344,both
3,2,ciudad autónoma de buenos aires,2001,comuna 1,2020,9773,221001,4422.151936,4.422152,GBA,...,ciudad autónoma de buenos aires,-0.906055,325.364358,-34.606444,-58.371512,ciudad autonoma de buenos aires,comuna 1,256405.0,17.774344,both
4,2,ciudad autónoma de buenos aires,2001,comuna 1,2021,13012,221001,5887.756164,5.887756,GBA,...,ciudad autónoma de buenos aires,5.042552,478.615058,-34.606444,-58.371512,ciudad autonoma de buenos aires,comuna 1,257235.0,17.774344,both

### Se detectaron inconsistencias menores entre fuentes territoriales (SNIC vs estimaciones poblacionales), resultando en un pequeño porcentaje de observaciones sin correspondencia. Estos casos fueron conservados en el dataset, identificados mediante una variable de control, y no afectan significativamente el análisis global.

In [95]:
# Etiquetar casos faltantes
df_mapa_sup_final["flag_poblacion_faltante"] = df_mapa_sup_final["poblacion"].isna()
df_mapa_sup_final["flag_poblacion_faltante"].sum()

np.int64(8)

### Crear la nueva tasa de delitos con las proyecciones de poblacion

In [96]:
df_mapa_sup_final["tasa_delitos_propiedad_100k_v2"] = (
    df_mapa_sup_final["delitos_propiedad_hechos"] / df_mapa_sup_final["poblacion"]
) * 100000

### Calcular la densidad de la poblacion en cada departamento

In [97]:
df_mapa_sup_final["densidad_poblacion"] = (
    df_mapa_sup_final["poblacion"] / df_mapa_sup_final["Superficie en km2"]
)

# Creación de varibles Lag

In [98]:
import numpy as np

# 0) Ordenar panel por provincia, departamento y año para asegurar que los lags estén correctos
df_mapa_sup_final = df_mapa_sup_final.sort_values(
    ["provincia_key", "departamento_key", "anio"]
)

# 1) Lag del target
df_mapa_sup_final["tasa_lag1"] = df_mapa_sup_final.groupby(
    ["provincia_key", "departamento_key"]
)["tasa_delitos_propiedad_100k_v2"].shift(1)

# 2) Lags de variables externas
df_mapa_sup_final["Indice_IPC_lag1"] = df_mapa_sup_final.groupby(
    ["provincia_key", "departamento_key"]
)["Indice_IPC"].shift(1)

df_mapa_sup_final["variacion_anual_cbt_lag1"] = df_mapa_sup_final.groupby(
    ["provincia_key", "departamento_key"]
)["variacion_anual_cbt"].shift(1)

df_mapa_sup_final["variacion_anual_salarios_lag1"] = df_mapa_sup_final.groupby(
    ["provincia_key", "departamento_key"]
)["variacion_anual_salarios_pct"].shift(1)

# 3) Crecimiento interanual del target
df_mapa_sup_final["tasa_yoy"] = df_mapa_sup_final.groupby(
    ["provincia_key", "departamento_key"]
)["tasa_delitos_propiedad_100k_v2"].pct_change(fill_method=None)

# 4) Log de densidad
df_mapa_sup_final["log_densidad"] = np.log(
    df_mapa_sup_final["densidad_poblacion"] + 1
)

In [99]:
# Guardar el dataset
df_mapa_sup_final.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/final/dataset_mapa_sup_final.csv", index=False)

In [ ]:
df_mapa_sup_final.columns.tolist()

['provincia_id',
 'provincia_nombre',
 'departamento_id',
 'departamento_nombre',
 'anio',
 'delitos_propiedad_hechos',
 'poblacion_2022',
 'tasa_delitos_propiedad_100k',
 'tasa_delitos_propiedad_pct',
 'region',
 'variacion_anual_salarios_pct',
 'variacion_anual_cbt',
 'variacion_empleo_const_pct',
 'mes',
 'variacion_anual_ipim',
 'jurisdiccion',
 'variacion_acceso_internet_pct',
 'Indice_IPC',
 'lat',
 'lon',
 'provincia_key',
 'departamento_key',
 'poblacion',
 'Superficie en km2',
 '_merge',
 'flag_poblacion_faltante',
 'tasa_delitos_propiedad_100k_v2',
 'densidad_poblacion',
 'tasa_lag1',
 'Indice_IPC_lag1',
 'variacion_anual_cbt_lag1',
 'variacion_anual_salarios_lag1',
 'tasa_yoy',
 'log_densidad']

In [100]:
print(df_mapa_sup_final.columns.tolist())
df_mapa_sup_final.shape

['provincia_id', 'provincia_nombre', 'departamento_id', 'departamento_nombre', 'anio', 'delitos_propiedad_hechos', 'poblacion_2022', 'tasa_delitos_propiedad_100k', 'tasa_delitos_propiedad_pct', 'region', 'variacion_anual_salarios_pct', 'variacion_anual_cbt', 'variacion_empleo_const_pct', 'mes', 'variacion_anual_ipim', 'jurisdiccion', 'variacion_acceso_internet_pct', 'Indice_IPC', 'lat', 'lon', 'provincia_key', 'departamento_key', 'poblacion', 'Superficie en km2', '_merge', 'flag_poblacion_faltante', 'tasa_delitos_propiedad_100k_v2', 'densidad_poblacion', 'tasa_lag1', 'Indice_IPC_lag1', 'variacion_anual_cbt_lag1', 'variacion_anual_salarios_lag1', 'tasa_yoy', 'log_densidad']

(4072, 34)

In [101]:
# Verificar nulos en df_mapa_sup_final
null_counts = df_mapa_sup_final.isna().sum().sort_values(ascending=False)
null_ratios = (df_mapa_sup_final.isna().mean() * 100).sort_values(ascending=False)

print(null_counts)
print("\nPorcentaje de nulos por columna:")
print(null_ratios)

tasa_yoy                          536
tasa_lag1                         530
variacion_anual_salarios_lag1     523
Indice_IPC_lag1                   523
variacion_anual_cbt_lag1          523
tasa_delitos_propiedad_100k_v2      8
log_densidad                        8
poblacion                           8
Superficie en km2                   8
densidad_poblacion                  8
provincia_nombre                    0
provincia_id                        0
departamento_id                     0
departamento_nombre                 0
poblacion_2022                      0
tasa_delitos_propiedad_100k         0
anio                                0
delitos_propiedad_hechos            0
Indice_IPC                          0
variacion_acceso_internet_pct       0
jurisdiccion                        0
variacion_anual_ipim                0
mes                                 0
variacion_empleo_const_pct          0
variacion_anual_cbt                 0
variacion_anual_salarios_pct        0
region                              0
tasa_delitos_propiedad_pct          0
flag_poblacion_faltante             0
_merge                              0
lon                                 0
lat                                 0
provincia_key                       0
departamento_key                    0
dtype: int64

Porcentaje de nulos por columna:
tasa_yoy                          13.163065
tasa_lag1                         13.015717
variacion_anual_salarios_lag1     12.843811
Indice_IPC_lag1                   12.843811
variacion_anual_cbt_lag1          12.843811
tasa_delitos_propiedad_100k_v2     0.196464
log_densidad                       0.196464
poblacion                          0.196464
Superficie en km2                  0.196464
densidad_poblacion                 0.196464
provincia_nombre                   0.000000
provincia_id                       0.000000
departamento_id                    0.000000
departamento_nombre                0.000000
poblacion_2022                     0.000000
tasa_delitos_propiedad_100k        0.000000
anio                               0.000000
delitos_propiedad_hechos           0.000000
Indice_IPC                         0.000000
variacion_acceso_internet_pct      0.000000
jurisdiccion                       0.000000
variacion_anual_ipim               0.000000
mes                                0.000000
variacion_empleo_const_pct         0.000000
variacion_anual_cbt                0.000000
variacion_anual_salarios_pct       0.000000
region                             0.000000
tasa_delitos_propiedad_pct         0.000000
flag_poblacion_faltante            0.000000
_merge                             0.000000
lon                                0.000000
lat                                0.000000
provincia_key                      0.000000
departamento_key                   0.000000
dtype: float64