In [1]:
import pandas as pd

In [2]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Procesar variable IPC

In [3]:


df_ipc = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/INDEC/serie_ipc_divisiones.csv",
                       encoding="latin1",
    sep=";")

In [4]:
print(df_ipc.columns.tolist())
print(df_ipc.shape)
df_ipc.head(10)

['Codigo', 'Descripcion', 'Clasificador', 'Periodo', 'Indice_IPC', 'v_m_IPC', 'v_i_a_IPC', 'Region']
(13986, 8)

,Codigo,Descripcion,Clasificador,Periodo,Indice_IPC,v_m_IPC,v_i_a_IPC,Region
0,0,NIVEL GENERAL,Nivel general y divisiones COICOP,201612,100,NaN,NaN,GBA
1,0,NIVEL GENERAL,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Pampeana
2,0,NIVEL GENERAL,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Noreste
3,0,NIVEL GENERAL,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Noroeste
4,0,NIVEL GENERAL,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Cuyo
5,0,NIVEL GENERAL,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Patagonia
6,0,NIVEL GENERAL,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Nacional
7,01,Alimentos y bebidas no alcohólicas,Nivel general y divisiones COICOP,201612,100,NaN,NaN,GBA
8,01,Alimentos y bebidas no alcohólicas,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Pampeana
9,01,Alimentos y bebidas no alcohólicas,Nivel general y divisiones COICOP,201612,100,NaN,NaN,Noreste

In [5]:
# Filtrar solo el nivel general
df_ipc = df_ipc[df_ipc["Descripcion"] == "NIVEL GENERAL"]

In [6]:
# Reemplazar comas por puntos y convertir a float
df_ipc["Indice_IPC"] = df_ipc["Indice_IPC"].str.replace(",", ".").astype(float)

In [7]:
# Convertir la columna "Periodo" a formato datetime
df_ipc["Periodo"] = df_ipc["Periodo"].astype(str)

df_ipc["fecha"] = pd.to_datetime(df_ipc["Periodo"], format="%Y%m")
df_ipc["anio"] = df_ipc["fecha"].dt.year

In [8]:
# Crear un diccionario de mapeo para las regiones
map_region = {
    "GBA": "gba",
    "Pampeana": "pampeana",
    "Noreste": "nea",
    "Noroeste": "noa",
    "Cuyo": "cuyo",
    "Patagonia": "patagonia",
    "Nacional": "nacional"
}

df_ipc["region"] = df_ipc["Region"].map(map_region)

In [9]:
# Agrupar por región y año, y calcular el promedio del índice IPC
df_ipc_anual = (
    df_ipc
    .groupby(["region", "anio"])["Indice_IPC"]
    .mean()
    .reset_index()
)

In [10]:
# Filtrar para eliminar la región "nacional"
df_ipc_anual = df_ipc_anual [df_ipc_anual["region"] != "nacional"]

In [11]:
# Guardar el dataset procesado
df_ipc_anual.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/ipc.csv", index=False)

## Procesar variable Salarios

In [12]:
# Cargar el dataset de variación del índice de salarios
df_salarios = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/INDEC/variacion_indice_salarios.csv",
                          encoding="latin1", sep=";")

In [13]:
print(df_salarios.shape)
print(df_salarios.columns.tolist())
df_salarios

(124, 22)
['periodo', 'v_m_sector_privado_registrado', 'v_i_a_sector_privado_registrado', 'v_acum_sector_privado_registrado', 'v_m_sector_publico', 'v_i_a_sector_publico', 'v_acum_sector_publico', 'v_m_total_registrado', 'v_i_a_total_registrado', 'v_acum_total_registrado', 'v_m_sector_privado_no_registrado', 'v_i_a_sector_privado_no_registrado', 'v_acum_sector_privado_no_registrado', 'v_m_indice_total', 'v_i_a_indice_total', 'v_acum_indice_total', 'v_m_subsector_publico_nacional', 'v_i_a_subsector_publico_nacional', 'v_acum_subsector_publico_nacional', 'v_m_subsector_publico_provincial', 'v_i_a_subsector_publico_provincial', 'v_acum_subsector_publico_provincial']

,periodo,v_m_sector_privado_registrado,v_i_a_sector_privado_registrado,v_acum_sector_privado_registrado,v_m_sector_publico,v_i_a_sector_publico,v_acum_sector_publico,v_m_total_registrado,v_i_a_total_registrado,v_acum_total_registrado,...,v_acum_sector_privado_no_registrado,v_m_indice_total,v_i_a_indice_total,v_acum_indice_total,v_m_subsector_publico_nacional,v_i_a_subsector_publico_nacional,v_acum_subsector_publico_nacional,v_m_subsector_publico_provincial,v_i_a_subsector_publico_provincial,v_acum_subsector_publico_provincial
0,1/10/2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/11/2015,"2,68",NaN,NaN,"1,37",NaN,NaN,"2,19",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/12/2015,"1,86",NaN,NaN,"1,18",NaN,NaN,"1,6",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/1/2016,"2,02",NaN,"2,02","0,36",NaN,"0,36","1,41",NaN,"1,41",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/2/2016,"1,41",NaN,"3,47","1,16",NaN,"1,53","1,32",NaN,"2,74",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,1/9/2025,"1,37","32,92","20,44","1,14","35,04","23,86","1,3","33,61","21,54",...,"77,04","2,22","46,04","30,4","1,26","21,79","16,04","1,11","39,64","27,08"
120,1/10/2025,"2,08","30,53","22,94","1,89","31,87","26,2","2,02","30,96","23,99",...,"84,54","2,5","43,13","33,65","1,23","21,24","17,47","2,11","36,23","29,77"
121,1/11/2025,"2,13","29,07","25,57","1,15","29,84","27,65","1,81","29,32","26,24",...,"87,66","1,78","40,28","36,03","1,27","21,26","18,96","1,13","33,54","31,24"
122,1/12/2025,"2,53","28,74","28,74","0,99","28,91","28,91","2,03","28,8","28,8",...,"87,91","1,61","38,23","38,23","1,04","20,19","20,19","1,08","32,66","32,66"
123,1/1/2026,"2,13","28,53","2,13","1,81","30,04","1,81","2,03","29,01","2,03",...,"4,37","2,54","37,7","2,54","2,04","22,4","2,04","1,74","33,36","1,74"

In [14]:
# Quedarme solo con las columnas necesarias.
df_salarios = df_salarios[["periodo", "v_i_a_indice_total"]].copy()

# Renombrar las columnas para que sean más descriptivas.

df_salarios.rename(columns={"periodo": "fecha", "v_i_a_indice_total": "variacion_anual_salarios_pct"}, inplace=True)

df_salarios.head(35)

        fecha variacion_anual_salarios_pct
0   1/10/2015                          NaN
1   1/11/2015                          NaN
2   1/12/2015                          NaN
3    1/1/2016                          NaN
4    1/2/2016                          NaN
5    1/3/2016                          NaN
6    1/4/2016                          NaN
7    1/5/2016                          NaN
8    1/6/2016                          NaN
9    1/7/2016                          NaN
10   1/8/2016                          NaN
11   1/9/2016                          NaN
12  1/10/2016                          NaN
13  1/11/2016                          NaN
14  1/12/2016                          NaN
15   1/1/2017                          NaN
16   1/2/2017                          NaN
17   1/3/2017                          NaN
18   1/4/2017                          NaN
19   1/5/2017                          NaN
20   1/6/2017                          NaN
21   1/7/2017                          NaN
22   1/8/2017                          NaN
23   1/9/2017                          NaN
24  1/10/2017                        27,62
25  1/11/2017                         27,8
26  1/12/2017                        27,47
27   1/1/2018                        26,92
28   1/2/2018                        26,31
29   1/3/2018                        25,11
30   1/4/2018                        24,13
31   1/5/2018                        24,03
32   1/6/2018                        22,92
33   1/7/2018                        21,31
34   1/8/2018                        21,86

In [15]:
# Pasar fecha a formato datetime
df_salarios["fecha"] = pd.to_datetime(df_salarios["fecha"], dayfirst=True)

In [16]:
# Convertir la variación anual de salarios a formato numérico

df_salarios["variacion_anual_salarios_pct"] = df_salarios["variacion_anual_salarios_pct"].astype(str).str.replace(",", ".", regex=False).astype(float)

df_salarios["variacion_anual_salarios_pct"] = pd.to_numeric(df_salarios["variacion_anual_salarios_pct"], errors='coerce').round(2)

In [17]:
# Tomar año y mes de la fecha
df_salarios["anio"] = df_salarios["fecha"].dt.year
df_salarios["mes"] = df_salarios["fecha"].dt.month

In [18]:
df_salarios.head(10)

       fecha  variacion_anual_salarios_pct  anio  mes
0 2015-10-01                           NaN  2015   10
1 2015-11-01                           NaN  2015   11
2 2015-12-01                           NaN  2015   12
3 2016-01-01                           NaN  2016    1
4 2016-02-01                           NaN  2016    2
5 2016-03-01                           NaN  2016    3
6 2016-04-01                           NaN  2016    4
7 2016-05-01                           NaN  2016    5
8 2016-06-01                           NaN  2016    6
9 2016-07-01                           NaN  2016    7

In [19]:
# tomar mes de Diciembre de cada año para obtener la variacion anual de salarios
df_salarios_anual = df_salarios[df_salarios["mes"] == 12][["anio", "variacion_anual_salarios_pct"]].copy()

In [20]:
# Ordenar por año
df_salarios_anual = df_salarios_anual.sort_values("anio").reset_index(drop=True)
df_salarios_anual

    anio  variacion_anual_salarios_pct
0   2015                           NaN
1   2016                           NaN
2   2017                         27.47
3   2018                         29.71
4   2019                         40.89
5   2020                         32.99
6   2021                         53.36
7   2022                         90.36
8   2023                        152.68
9   2024                        145.47
10  2025                         38.23

La variación salarial anual se calcula utilizando la variación interanual del índice total correspondiente al mes de diciembre de cada año. Para 2016 no se dispone de valor interanual completo, por lo que se considera como dato faltante.

In [21]:
# Guardar el dataframe procesado
df_salarios_anual.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/salarios_variacion_anual.csv", index=False)

# Procesar variable Canasta Básica Total

In [22]:
# Cargar el dataset
df_cbt = pd.read_excel(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/INDEC/Cba_y_Cbt.xlsx")

print(df_cbt.columns.tolist())
print(df_cbt.info())
df_cbt.head(19)

['Mes', 'Canasta básica alimentaria', 'Inversa del coeficiente de Engel', 'Canasta básica total']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Mes                               120 non-null    object
 1   Canasta básica alimentaria        121 non-null    object
 2   Inversa del coeficiente de Engel  119 non-null    float64
 3   Canasta básica total              121 non-null    object
dtypes: float64(1), object(3)
memory usage: 4.0+ KB
None

,Mes,Canasta básica alimentaria,Inversa del coeficiente de Engel,Canasta básica total
0,NaN,Línea de indigencia,NaN,Línea de pobreza
1,NaN,(Valor en $),NaN,(Valor en $)
2,NaN,NaN,NaN,NaN
3,2016-04-01 00:00:00,1514.53,2.42,3663.66
4,2016-05-01 00:00:00,1561.35,2.45,3830.77
5,2016-06-01 00:00:00,1614.32,2.44,3942.67
6,2016-07-01 00:00:00,1666.48,2.42,4033.76
7,2016-08-01 00:00:00,1675.05,2.41,4041.87
8,2016-09-01 00:00:00,1711.22,2.39,4089.82
9,2016-10-01 00:00:00,1739.34,2.41,4191.81
10,2016-11-01 00:00:00,1762.65,2.41,4247.99
11,2016-12-01 00:00:00,1766.62,2.41,4257.55
12,2017-01-01 00:00:00,1789.15,2.41,4311.85
13,2017-02-01 00:00:00,1821.02,2.43,4425.08
14,2017-03-01 00:00:00,1876.56,2.43,4560.04
15,2017-04-01 00:00:00,1915.47,2.45,4692.9
16,2017-05-01 00:00:00,1937.24,2.45,4746.24
17,2017-06-01 00:00:00,1956.42,2.45,4793.23
18,2017-07-01 00:00:00,1984.64,2.45,4862.37

In [23]:
# 1. Limpiar filas basura
df_cbt = df_cbt[pd.to_datetime(df_cbt["Mes"], errors="coerce").notna()].copy()

In [24]:
# Renombrar columnas para que sean más descriptivas
df_cbt =df_cbt.rename(columns={"Mes": "fecha", "Canasta básica total": "cbt"})

In [25]:
# Convertir a tipos fecha y numérico
df_cbt["fecha"] = pd.to_datetime(df_cbt["fecha"])

df_cbt["cbt"] = pd.to_numeric(df_cbt["cbt"], errors="coerce")

In [26]:
# Crear año y mes
df_cbt["anio"] = df_cbt["fecha"].dt.year
df_cbt["mes"] = df_cbt["fecha"].dt.month

# calculo la variacion

df_cbt = df_cbt.sort_values("fecha")
df_cbt["variacion_anual_cbt"] = (df_cbt["cbt"].pct_change(periods=12) * 100).round(2)

df_cbt.tail(20)

,fecha,Canasta básica alimentaria,Inversa del coeficiente de Engel,cbt,anio,mes,variacion_anual_cbt
102,2024-07-01,131293.57,2.22,291471.73,2024,7,261.76
103,2024-08-01,136399.3,2.23,304170.44,2024,8,230.15
104,2024-09-01,138744.31,2.25,312174.70,2024,9,201.99
105,2024-10-01,140653.57,2.27,319283.60,2024,10,185.72
106,2024-11-01,142148.73,2.28,324099.10,2024,11,156.49
107,2024-12-01,145408.96,2.28,331532.43,2024,12,106.62
108,2025-01-01,146726.23,2.28,334535.80,2025,1,73.20
109,2025-02-01,151491.17,2.26,342370.04,2025,2,53.12
110,2025-03-01,160393.45,2.22,356073.46,2025,3,42.27
111,2025-04-01,162553.77,2.21,359243.83,2025,4,34.04
112,2025-05-01,161903.21,2.22,359425.13,2025,5,30.45
113,2025-06-01,163756.66,2.23,365177.35,2025,6,29.23
114,2025-07-01,166797.7,2.23,371958.87,2025,7,27.61
115,2025-08-01,168456.04,2.23,375656.97,2025,8,23.50
116,2025-09-01,170788.46,2.23,380858.27,2025,9,22.00
117,2025-10-01,176150.29,2.23,392815.15,2025,10,23.03
118,2025-11-01,183289.46,2.22,406902.60,2025,11,25.55
119,2025-12-01,190780.09,2.22,423531.80,2025,12,27.75
120,2026-01-01,201938.62,2.18,440226.19,2026,1,31.59
121,2026-02-01,208442.85,2.17,452320.98,2026,2,32.11

In [27]:
# Llevar a variacion anual de la cbt
df_cbt_anual = df_cbt[df_cbt["mes"]==12][["anio", "variacion_anual_cbt"]].copy()

df_cbt_anual = df_cbt_anual.sort_values("anio").reset_index(drop=True)
df_cbt_anual

   anio  variacion_anual_cbt
0  2016                  NaN
1  2017                26.77
2  2018                52.86
3  2019                52.82
4  2020                39.14
5  2021                40.47
6  2022               100.29
7  2023               225.08
8  2024               106.62
9  2025                27.75

In [28]:
# Guardar el dataframe procesado

df_cbt_anual.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/cbt_variacion_anual.csv")

# Procesar variable Puestos de Trabajo en la construcción

In [29]:
# cargar dataset
df_trab_constr = pd.read_excel(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/INDEC/Puestos_trab_const.xlsx")

print(df_trab_constr.columns.tolist())
print(df_trab_constr.info())
df_trab_constr.head(30)

['Período', 'Unnamed: 1', 'Puestos de trabajo', 'Variación porcentual', 'Unnamed: 4']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Período               11 non-null     object
 1   Unnamed: 1            132 non-null    object
 2   Puestos de trabajo    132 non-null    float64
 3   Variación porcentual  133 non-null    object
 4   Unnamed: 4            133 non-null    object
dtypes: float64(1), object(4)
memory usage: 5.8+ KB
None

,Período,Unnamed: 1,Puestos de trabajo,Variación porcentual,Unnamed: 4
0,NaN,NaN,NaN,respecto al mismo mes del año anterior,acumulada del año respecto a igual acumulado d...
1,NaN,NaN,NaN,NaN,NaN
2,2015 *,Enero,426885.000000,///,///
3,NaN,Febrero,430069.000000,///,///
4,NaN,Marzo,441669.000000,///,///
5,NaN,Abril,447691.000000,///,///
6,NaN,Mayo,451500.000000,///,///
7,NaN,Junio,458433.000000,///,///
8,NaN,Julio,458433.000000,///,///
9,NaN,Agosto,453605.000000,///,///
10,NaN,Septiembre,456354.000000,///,///
11,NaN,Octubre,455447.000000,///,///
12,NaN,Noviembre,448103.000000,///,///
13,NaN,Diciembre,421659.000000,///,///
14,NaN,NaN,NaN,NaN,NaN
15,2016 *,Enero,408799.000000,-4.236738,-4.236738
16,NaN,Febrero,403220.000000,-6.242952,-5.243572
17,NaN,Marzo,402102.000000,-8.958519,-6.507046
18,NaN,Abril,398869.000000,-10.90529,-7.634595
19,NaN,Mayo,398587.000000,-11.71938,-8.473738
20,NaN,Junio,396286.000000,-13.556398,-9.350938
21,NaN,Julio,395602.000000,-13.705601,-9.991877
22,NaN,Agosto,400965.000000,-11.60481,-10.196915
23,NaN,Septiembre,403928.000000,-11.488011,-10.343313
24,NaN,Octubre,406237.000000,-10.80477,-10.390225
25,NaN,Noviembre,412037.000000,-8.048596,-10.177309
26,NaN,Diciembre,403418.000000,-4.326008,-9.716127
27,NaN,NaN,NaN,NaN,NaN
28,2017 *,Enero,407245.604730,-0.37999,-0.37999
29,NaN,Febrero,410432.882302,1.788821,0.696965

In [30]:
# Eliminar filas basura
df_trab_constr = df_trab_constr.dropna(subset=["Puestos de trabajo"]).copy()
print(df_trab_constr.columns.tolist())
print(df_trab_constr.info())
df_trab_constr.head(30)

['Período', 'Unnamed: 1', 'Puestos de trabajo', 'Variación porcentual', 'Unnamed: 4']
<class 'pandas.core.frame.DataFrame'>
Index: 132 entries, 2 to 143
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Período               11 non-null     object
 1   Unnamed: 1            132 non-null    object
 2   Puestos de trabajo    132 non-null    float64
 3   Variación porcentual  132 non-null    object
 4   Unnamed: 4            132 non-null    object
dtypes: float64(1), object(4)
memory usage: 6.2+ KB
None

   Período  Unnamed: 1  Puestos de trabajo Variación porcentual Unnamed: 4
2   2015 *       Enero       426885.000000                  ///        ///
3      NaN     Febrero       430069.000000                  ///        ///
4      NaN       Marzo       441669.000000                  ///        ///
5      NaN       Abril       447691.000000                  ///        ///
6      NaN        Mayo       451500.000000                  ///        ///
7      NaN       Junio       458433.000000                  ///        ///
8      NaN       Julio       458433.000000                  ///        ///
9      NaN      Agosto       453605.000000                  ///        ///
10     NaN  Septiembre       456354.000000                  ///        ///
11     NaN     Octubre       455447.000000                  ///        ///
12     NaN   Noviembre       448103.000000                  ///        ///
13     NaN   Diciembre       421659.000000                  ///        ///
15  2016 *       Enero       408799.000000            -4.236738  -4.236738
16     NaN     Febrero       403220.000000            -6.242952  -5.243572
17     NaN       Marzo       402102.000000            -8.958519  -6.507046
18     NaN       Abril       398869.000000            -10.90529  -7.634595
19     NaN        Mayo       398587.000000            -11.71938  -8.473738
20     NaN       Junio       396286.000000           -13.556398  -9.350938
21     NaN       Julio       395602.000000           -13.705601  -9.991877
22     NaN      Agosto       400965.000000            -11.60481 -10.196915
23     NaN  Septiembre       403928.000000           -11.488011 -10.343313
24     NaN     Octubre       406237.000000            -10.80477 -10.390225
25     NaN   Noviembre       412037.000000            -8.048596 -10.177309
26     NaN   Diciembre       403418.000000            -4.326008  -9.716127
28  2017 *       Enero       407245.604730             -0.37999   -0.37999
29     NaN     Febrero       410432.882302             1.788821   0.696965
30     NaN       Marzo       423977.987752             5.440408   2.267935
31     NaN       Abril       420417.309876             5.402353   3.043031
32     NaN        Mayo       428903.848586             7.606081   3.947183
33     NaN       Junio       434173.341750             9.560606    4.87104

In [31]:
# renombrar columna
df_trab_constr = df_trab_constr.rename(columns={"Unnamed: 1": "mes", "Variación porcentual": "Variacion_pct_mes", "Unnamed: 4": "Variacion_pct_anual"})

In [32]:
# Reconstruir columna del año
df_trab_constr["anio"] = df_trab_constr["Período"].str.extract(r"(\d{4})")
df_trab_constr["anio"] = df_trab_constr["anio"].ffill()
df_trab_constr["anio"] = pd.to_numeric(df_trab_constr["anio"], errors="coerce")
df_trab_constr.head(30)

,Período,mes,Puestos de trabajo,Variacion_pct_mes,Variacion_pct_anual,anio
2,2015 *,Enero,426885.000000,///,///,2015
3,NaN,Febrero,430069.000000,///,///,2015
4,NaN,Marzo,441669.000000,///,///,2015
5,NaN,Abril,447691.000000,///,///,2015
6,NaN,Mayo,451500.000000,///,///,2015
7,NaN,Junio,458433.000000,///,///,2015
8,NaN,Julio,458433.000000,///,///,2015
9,NaN,Agosto,453605.000000,///,///,2015
10,NaN,Septiembre,456354.000000,///,///,2015
11,NaN,Octubre,455447.000000,///,///,2015
12,NaN,Noviembre,448103.000000,///,///,2015
13,NaN,Diciembre,421659.000000,///,///,2015
15,2016 *,Enero,408799.000000,-4.236738,-4.236738,2016
16,NaN,Febrero,403220.000000,-6.242952,-5.243572,2016
17,NaN,Marzo,402102.000000,-8.958519,-6.507046,2016
18,NaN,Abril,398869.000000,-10.90529,-7.634595,2016
19,NaN,Mayo,398587.000000,-11.71938,-8.473738,2016
20,NaN,Junio,396286.000000,-13.556398,-9.350938,2016
21,NaN,Julio,395602.000000,-13.705601,-9.991877,2016
22,NaN,Agosto,400965.000000,-11.60481,-10.196915,2016
23,NaN,Septiembre,403928.000000,-11.488011,-10.343313,2016
24,NaN,Octubre,406237.000000,-10.80477,-10.390225,2016
25,NaN,Noviembre,412037.000000,-8.048596,-10.177309,2016
26,NaN,Diciembre,403418.000000,-4.326008,-9.716127,2016
28,2017 *,Enero,407245.604730,-0.37999,-0.37999,2017
29,NaN,Febrero,410432.882302,1.788821,0.696965,2017
30,NaN,Marzo,423977.987752,5.440408,2.267935,2017
31,NaN,Abril,420417.309876,5.402353,3.043031,2017
32,NaN,Mayo,428903.848586,7.606081,3.947183,2017
33,NaN,Junio,434173.341750,9.560606,4.87104,2017

In [33]:
# mapear meses a números
map_meses = {
    "Enero": 1, "Febrero": 2, "Marzo": 3, "Abril": 4,
    "Mayo": 5, "Junio": 6, "Julio": 7, "Agosto": 8,
    "Septiembre": 9, "Octubre": 10, "Noviembre": 11, "Diciembre": 12
}

df_trab_constr["mes_num"] = df_trab_constr["mes"].map(map_meses)
df_trab_constr.head()

,Período,mes,Puestos de trabajo,Variacion_pct_mes,Variacion_pct_anual,anio,mes_num
2,2015 *,Enero,426885.0,///,///,2015,1
3,NaN,Febrero,430069.0,///,///,2015,2
4,NaN,Marzo,441669.0,///,///,2015,3
5,NaN,Abril,447691.0,///,///,2015,4
6,NaN,Mayo,451500.0,///,///,2015,5

In [34]:
# Limpiar variacion interanual de puestos de trabajo
df_trab_constr["variacion_pct"] = pd.to_numeric(df_trab_constr["Variacion_pct_anual"].astype(str).str.replace(",",".", regex=False).replace("///", None))
df_trab_constr["variacion_pct"] = pd.to_numeric(df_trab_constr["variacion_pct"], errors="coerce")
df_trab_constr

,Período,mes,Puestos de trabajo,Variacion_pct_mes,Variacion_pct_anual,anio,mes_num,variacion_pct
2,2015 *,Enero,426885.000000,///,///,2015,1,NaN
3,NaN,Febrero,430069.000000,///,///,2015,2,NaN
4,NaN,Marzo,441669.000000,///,///,2015,3,NaN
5,NaN,Abril,447691.000000,///,///,2015,4,NaN
6,NaN,Mayo,451500.000000,///,///,2015,5,NaN
...,...,...,...,...,...,...,...,...
139,NaN,Agosto,375417.584330,0.305438,-1.253413,2025,8,-1.253413
140,NaN,Septiembre,380227.728964,0.882976,-1.017188,2025,9,-1.017188
141,NaN,Octubre,383085.314453,1.120208,-0.803396,2025,10,-0.803396
142,NaN,Noviembre,380320.744243,0.740794,-0.663428,2025,11,-0.663428
143,NaN,Diciembre,380879.712994,3.267908,-0.343614,2025,12,-0.343614

In [35]:
# Quedarme solo con diciembre de cada año
df_trab_constr_anual = df_trab_constr[df_trab_constr["mes_num"]==12][["anio", "variacion_pct"]].copy()

In [36]:
# Ordenar
df_trab_constr_anual = df_trab_constr_anual.sort_values("anio").reset_index(drop=True)
df_trab_constr_anual

    anio  variacion_pct
0   2015            NaN
1   2016      -9.716127
2   2017       7.865122
3   2018       2.804384
4   2019      -4.095870
5   2020     -22.513076
6   2021      10.894769
7   2022      16.258769
8   2023       6.451770
9   2024     -17.002318
10  2025      -0.343614

In [37]:
# Renombrar columna PRINCIPAL
df_trab_constr_anual = df_trab_constr_anual.rename(columns={"variacion_pct": "variacion_empleo_const_pct"})

In [38]:
# guardar el dataframe procesado
df_trab_constr_anual.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/empleo_const_anual.csv")

# Procesar variable Indice IPIM

In [39]:
# cargar dataset
df_ipim = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/INDEC/indice_ipim.csv", encoding="latin1", sep=";")
print(df_ipim.columns.tolist())
print(df_ipim.info())
df_ipim.head(15)

['periodo', 'nivel_general_aperturas', 'indice_ipim']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16974 entries, 0 to 16973
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   periodo                  16974 non-null  object
 1   nivel_general_aperturas  16974 non-null  object
 2   indice_ipim              16974 non-null  object
dtypes: object(3)
memory usage: 398.0+ KB
None

       periodo nivel_general_aperturas       indice_ipim
0   2015-12-01        ng_nivel_general               100
1   2016-01-01        ng_nivel_general  108,787179072642
2   2016-02-01        ng_nivel_general  114,170884286305
3   2016-03-01        ng_nivel_general  117,000647955677
4   2016-04-01        ng_nivel_general  118,812575925872
5   2016-05-01        ng_nivel_general  123,099353635332
6   2016-06-01        ng_nivel_general  126,681921953781
7   2016-07-01        ng_nivel_general  130,208352107735
8   2016-08-01        ng_nivel_general  130,722590357452
9   2016-09-01        ng_nivel_general  131,280553423565
10  2016-10-01        ng_nivel_general  132,059366852626
11  2016-11-01        ng_nivel_general  133,678918859084
12  2016-12-01        ng_nivel_general  134,528991476547
13  2017-01-01        ng_nivel_general  136,545907312244
14  2017-02-01        ng_nivel_general   138,82611252137

In [40]:
print(df_ipim["nivel_general_aperturas"].unique())
df_ipim["nivel_general_aperturas"].unique().shape

['ng_nivel_general' 'n_productos_nacionales' '1_primarios'
 'a_productos_agropecuarios' '011_agricolas' '0111_cereales_y_oleaginosas'
 '0112_hortalizas_y_legumbres' '0113_frutas' '012_ganaderos'
 '0121_ganado_vacuno_y_leche' '0122_ganado_porcino_y_productos de granja'
 'b_productos_pesqueros' 'c_productos_minerales'
 '11_petroleo_crudo_y_gas_natural' '14_productos_minerales_no_metaliferos'
 '2_industria_manufacturera_ y_energia_electrica'
 'd_productos_manufacturados' '15_alimentos_y_bebidas'
 '151_productos_de_carnes_pescados_frutas_legumbres_hortalizas_y_aceites'
 '1511_productos_carnicos' '1512_conservas_de_pescados'
 '1513_conservas_de_frutas_hortalizas_y_legumbres'
 '1514_aceites_y_grasas_vegetales' '152_productos_lacteos'
 '153_productos_de_molineria_almidones_y_alimentos_balanceados'
 '1531_harinas' '1532_productos_derivados_del_almidon'
 '1533_alimentos_balanceados' '154_otros_productos_alimenticios'
 '1541_productos_de_panaderia' '1542_azucar'
 '1543_productos_de_chocolate_y_golosinas' '1544_productos_farinaceos'
 '1549_otros_productos_alimenticios_n.c.e.p.'
 '155_alcohol_etilico_y_bebidas'
 '1551_alcohol_etilico_y_bebidas_alcoholicas_destiladas'
 '1552_vinos_y_sidra' '1553_cervezas' '1554_bebidas_no_alcoholicas'
 '16_tabaco' '17_productos_textiles' '171_materias_primas_textiles'
 '172_otros_productos_textiles' '173_tejidos_y_articulos_de_punto'
 '18_prendas_de_materiales_textiles'
 '19_cuero_articulos_de_marroquineria_y_calzado'
 '191_cueros_valijas_y_articulos_de_marroquineria' '1911_cueros_curtidos'
 '1912_valijas_y_articulos_de_marroquineria' '192_calzado'
 '20_madera_y_productos_de_madera_excepto_muebles' '201_maderas_aserradas'
 '202_productos_de_madera' '2021_tableros_y_paneles_de_madera'
 '2022_carpinteria_de_madera' '21_papel_y_productos_de_papel'
 '2101_papeles' '2102_envases_de_papel_y_carton'
 '2109_otros_articulos_de_papel_y_carton'
 '22_impresiones_y_reproduccion_de_grabaciones' '221_diarios_y_revistas'
 '222_articulos_de_libreria' '23_productos_refinados_del_petroleo'
 '24_sustancias_y_productos_quimicos' '241_sustancias_quimicas_basicas'
 '2411_sustancias_quimicas_basicas' '2412_abonos_y_fertilizantes'
 '2413_sustancias_plasticas_y_elastomeros' '242_otros_productos_quimicos'
 '2421_insecticidas_y_plaguicidas'
 '2422_pinturas_barnices_enduidos_y_tintas_de_imprenta'
 '2423_productos_farmaceuticos_y_veterinarios'
 '2424_jabones_y_detergentes' '2429_otros_productos_quimicos'
 '243_fibras_manufacturadas' '25_productos_de_caucho_y_plastico'
 '251_productos_de_caucho' '2511_cubiertas_de_caucho'
 '2519_otros_productos_de_caucho' '252_productos_de_plastico'
 '26_productos_de_minerales_no_metalicos'
 '261_vidrio_y_productos_de_vidrio'
 '269_otros_productos_de_minerales_no_metalicos'
 '2691_productos_de_ceramica_no_refractaria_para_uso_no_estructural'
 '2692_productos_de_ceramica_refractaria'
 '2693_productos_de_arcilla_y_ceramica_no_refractaria_para_uso_estructural'
 '2694_cemento_y_cal' '2695_articulos_de_hormigon_de_cemento_y_de_yeso'
 '2699_otros_articulos_de_minerales_no_metaliferos_n.c.e.p.'
 '27_productos_metalicos_basicos'
 '271_productos_de_minerales_ferrosos_en_formas_basicas'
 '272_productos_de_minerales_no_ferrosos_en_formas_basicas'
 '273_productos_de_fundicion'
 '28_productos_metalicos_excepto_maquinas_y_equipos'
 '281_productos_metalicos_estructurales_recipientes_y_generadores_de_vapor'
 '2811_productos_metalicos_para_uso_estructural'
 '2813_generadores_de_vapor'
 '289_otros_productos_metalicos_excepto_maquinas_equipos_y_muebles'
 '2893_herramientas_de mano_y_articulos_de_ferreteria'
 '2899_otros_productos_metalicos_n.c.e.p.' '29_maquinas_y_equipos'
 '291_maquinas_de_uso_general'
 '2911_motores_a_explosion_excepto_para_automotores'
 '2912_bombas_y_compresores' '2913_rodamientos'
 '2915_equipos_de_elevacion_y_manipulacion'
 '2919_otra_maquinaria_de_uso_general' '292_maquinas_de_uso_especial'
 '2921_maquinas_agricolas' '2922_maquinas_herramientas'
 '2924_maquinas_para_la_industria_extractiva_y_obras_de_construccion'
 '2925_maquinas_para_la_elaboracion_o_procesamiento_de_alimentos_y_bebidas'
 '2926_maquinas_para_lavaderos_industriales' '2927_armas_y_municiones'
 '293_otros_aparatos_de_uso_domestico' '31_maquinas_y_aparatos_electricos'
 '311_motores_generadores_y_transformadores_electricos'
 '312_aparatos_de_distribucion_y_control_electrico'
 '313_conductores_electricos' '314_acumuladores_electricos'
 '315_equipos_de_iluminacion' '319_otros_equipos_electricos'
 '32_equipos_y_aparatos_de_radio_y_television'
 '33_equipos_para_medicina_e_instrumentos_de_medicion'
 '3311_equipos_para_medicina'
 '3312_instrumentos_de_medicion_de_servicios_domiciliarios'
 '34_vehiculos_automotores_carrocerias_y_repuestos'
 '341_vehiculos_automotores' '342_carrocerias_y_remolques'
 '343_repuestos_para_automotores' '35_otros_medios_de_transporte'
 '3591_motocicletas' '3599_otros_medios_de_transporte'
 '36_muebles_y_otros_productos_industriales' '361_muebles_y_colchones'
 '369_otros_productos_manufacturados' 'e_energia_electrica'
 'i_productos_importados']

(138,)

In [41]:
# convertir fecha a formato datetime e indice a formato numérico
df_ipim["fecha"]= pd.to_datetime(df_ipim["periodo"] )
df_ipim["indice_ipim"] = (df_ipim["indice_ipim"].str.replace(",",".", regex=False))
df_ipim["indice_ipim"] = pd.to_numeric(df_ipim["indice_ipim"], errors="coerce")

In [42]:
# Filtrar df_ipim quedandome solo con los valores de apertura para "ng_nivel_general"
df_ipim = df_ipim[
    df_ipim["nivel_general_aperturas"] == "ng_nivel_general"
].reset_index(drop=True)

In [43]:
df_ipim.shape

(123, 4)

In [44]:
# Crear año y mes
df_ipim["anio"]= df_ipim["fecha"].dt.year
df_ipim["mes"]= df_ipim["fecha"].dt.month
print(df_ipim.shape)
df_ipim.head()

(123, 6)

      periodo nivel_general_aperturas  indice_ipim      fecha  anio  mes
0  2015-12-01        ng_nivel_general   100.000000 2015-12-01  2015   12
1  2016-01-01        ng_nivel_general   108.787179 2016-01-01  2016    1
2  2016-02-01        ng_nivel_general   114.170884 2016-02-01  2016    2
3  2016-03-01        ng_nivel_general   117.000648 2016-03-01  2016    3
4  2016-04-01        ng_nivel_general   118.812576 2016-04-01  2016    4

In [45]:
# Calcular la variación anual del IPIM
df_ipim = df_ipim.sort_values("fecha")
df_ipim["variacion_anual_ipim"] = (df_ipim["indice_ipim"].pct_change(periods=12) * 100).round(2)

In [46]:
# Pasar a anual quedandome con el mes de diciembre de cada año
df_ipim_anual = df_ipim[df_ipim["mes"]==12][["anio", "mes", "variacion_anual_ipim"]].copy()

#ordenar por año
df_ipim_anual = df_ipim_anual.sort_values("anio").reset_index(drop=True)

df_ipim_anual

    anio  mes  variacion_anual_ipim
0   2015   12                   NaN
1   2016   12                 34.53
2   2017   12                 18.85
3   2018   12                 73.50
4   2019   12                 58.49
5   2020   12                 35.38
6   2021   12                 51.34
7   2022   12                 94.78
8   2023   12                276.35
9   2024   12                 67.10
10  2025   12                 26.21

In [47]:
# Guardar el dataframe procesado
df_ipim_anual.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/ipim_variacion_anual.csv", index=False)

# Procesar variable de Accesos a Internet

In [48]:
df_acceso_internet = pd.read_excel(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/INDEC/Accesos_internet_prov.xlsx")
print(df_acceso_internet.columns.tolist())
print(df_acceso_internet.info())
df_acceso_internet.head(20)

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Columns: 110 entries, Unnamed: 0 to Unnamed: 109
dtypes: object(110)
memory usage: 23.3+ KB
None

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109
0,Jurisdicción,2016,2017,2017,2017,2017,2017,2017,2017,2017,...,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025
1,NaN,Diciembre,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Total del país,36970995,37009287,36738785,37031805,37164316,37270125,37402949,37821611,38131557,...,47811939,47719937,48203217,48281438,48563962,48763147,48881612,48941043,48858798,49008621
4,CABA y provincia de Buenos Aires,19083297,19083926,19014372,19120299,19208981,19201817,19248981,19433980,19576824,...,24095012,24062133,24343774,24396662,24516547,24629622,24720526,24737418,24725466,24762945
5,Catamarca,270757,271259,266050,269924,270853,272250,273965,278611,282015,...,369194,367180,369778,370013,372895,374175,373351,373931,372325,374019
6,Chaco,704496,710981,701466,711177,717414,730099,743305,761035,773619,...,1064466,1060801,1066734,1066211,1074327,1076636,1076111,1079508,1072866,1081694
7,Chubut,615952,614984,611944,616500,615247,618447,621407,626069,634490,...,677898,675832,683282,683563,684619,686281,687528,685655,682385,685922
8,Córdoba,3246615,3241326,3209987,3242457,3255079,3258878,3265460,3317500,3346495,...,4084063,4074158,4101417,4103723,4131051,4143963,4155368,4171497,4172026,4192641
9,Corrientes,727889,732969,727357,738043,738782,745784,752594,765192,776298,...,1067905,1068114,1076556,1075010,1083711,1088660,1087936,1090179,1084028,1088755
10,Entre Ríos,994765,998959,985462,995416,1001448,1008944,1014315,1029704,1039938,...,1363837,1361309,1371549,1371678,1381992,1386762,1387625,1391901,1389282,1397711
11,Formosa,347837,348455,341668,345732,347174,352290,356077,366612,372342,...,519173,517245,521585,524152,531296,532224,531834,534429,530668,534198
12,Jujuy,479872,481554,473633,480714,480597,483134,485166,494239,501422,...,693463,691531,694804,695522,700736,703578,702279,704940,702867,709345
13,La Pampa,284603,284071,282779,284912,285200,283970,286052,289962,292592,...,354201,353534,356556,356819,358655,360450,361137,360851,360170,360345
14,La Rioja,290358,291569,285959,289365,290825,293816,295429,300780,304823,...,437324,435991,439514,439788,442773,443534,444296,444997,443588,445974
15,Mendoza,1400855,1400734,1391031,1406793,1403990,1397910,1396098,1403612,1411577,...,1770822,1763964,1783023,1783442,1792037,1799676,1805472,1804333,1800425,1804410
16,Misiones,733565,737915,724728,735728,745852,756442,765995,785255,795898,...,1140748,1135915,1143775,1143008,1152823,1154224,1150954,1149166,1140759,1146388
17,Neuquén,691142,692987,691570,697501,694839,704797,705725,702185,704920,...,897923,896561,908472,910584,915242,919488,922663,921754,918116,919267
18,Río Negro,555067,560619,559432,564724,556140,568210,569786,557735,560205,...,614621,612147,623668,625941,628623,632189,635675,633702,629359,628085
19,Salta,869713,872018,854603,869909,872796,877307,882202,899731,907517,...,1273695,1272739,1279889,1280927,1292108,1294623,1292453,1295983,1290331,1298678

In [49]:
# Reconstruir correctamente los nombres de columnas del Excel
# Tomo las dos primeras filas como encabezados
fila_anios = df_acceso_internet.iloc[0]
fila_meses = df_acceso_internet.iloc[1]

# Construir nombres de columnas nuevos
nuevas_columnas = []

for i in range(len(df_acceso_internet.columns)):
    # La primera columna es la provincia/jurisdicción
    if i == 0:
        nuevas_columnas.append("jurisdiccion")
    else:
        anio = fila_anios.iloc[i]
        mes = fila_meses.iloc[i]
        nuevas_columnas.append(f"{anio}_{mes}")

# Aplicamos los nuevos nombres
df_acceso_internet.columns = nuevas_columnas

# Miramos cómo quedó
print(df_acceso_internet.columns.tolist()[:15])
df_acceso_internet.head(5)

['jurisdiccion', '2016_Diciembre', '2017_Enero', '2017_Febrero', '2017_Marzo', '2017_Abril', '2017_Mayo', '2017_Junio', '2017_Julio', '2017_Agosto', '2017_Septiembre', '2017_Octubre', '2017_Noviembre', '2017_Diciembre', '2018_Enero']

,jurisdiccion,2016_Diciembre,2017_Enero,2017_Febrero,2017_Marzo,2017_Abril,2017_Mayo,2017_Junio,2017_Julio,2017_Agosto,...,2025_Marzo,2025_Abril,2025_Mayo,2025_Junio,2025_Julio,2025_Agosto,2025_Septiembre,2025_Octubre,2025_Noviembre,2025_Diciembre
0,Jurisdicción,2016,2017,2017,2017,2017,2017,2017,2017,2017,...,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025
1,NaN,Diciembre,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Total del país,36970995,37009287,36738785,37031805,37164316,37270125,37402949,37821611,38131557,...,47811939,47719937,48203217,48281438,48563962,48763147,48881612,48941043,48858798,49008621
4,CABA y provincia de Buenos Aires,19083297,19083926,19014372,19120299,19208981,19201817,19248981,19433980,19576824,...,24095012,24062133,24343774,24396662,24516547,24629622,24720526,24737418,24725466,24762945

In [50]:
df_acceso_internet = df_acceso_internet.iloc[3:].reset_index(drop=True)
df_acceso_internet.head(10)

,jurisdiccion,2016_Diciembre,2017_Enero,2017_Febrero,2017_Marzo,2017_Abril,2017_Mayo,2017_Junio,2017_Julio,2017_Agosto,...,2025_Marzo,2025_Abril,2025_Mayo,2025_Junio,2025_Julio,2025_Agosto,2025_Septiembre,2025_Octubre,2025_Noviembre,2025_Diciembre
0,Total del país,36970995,37009287,36738785,37031805,37164316,37270125,37402949,37821611,38131557,...,47811939,47719937,48203217,48281438,48563962,48763147,48881612,48941043,48858798,49008621
1,CABA y provincia de Buenos Aires,19083297,19083926,19014372,19120299,19208981,19201817,19248981,19433980,19576824,...,24095012,24062133,24343774,24396662,24516547,24629622,24720526,24737418,24725466,24762945
2,Catamarca,270757,271259,266050,269924,270853,272250,273965,278611,282015,...,369194,367180,369778,370013,372895,374175,373351,373931,372325,374019
3,Chaco,704496,710981,701466,711177,717414,730099,743305,761035,773619,...,1064466,1060801,1066734,1066211,1074327,1076636,1076111,1079508,1072866,1081694
4,Chubut,615952,614984,611944,616500,615247,618447,621407,626069,634490,...,677898,675832,683282,683563,684619,686281,687528,685655,682385,685922
5,Córdoba,3246615,3241326,3209987,3242457,3255079,3258878,3265460,3317500,3346495,...,4084063,4074158,4101417,4103723,4131051,4143963,4155368,4171497,4172026,4192641
6,Corrientes,727889,732969,727357,738043,738782,745784,752594,765192,776298,...,1067905,1068114,1076556,1075010,1083711,1088660,1087936,1090179,1084028,1088755
7,Entre Ríos,994765,998959,985462,995416,1001448,1008944,1014315,1029704,1039938,...,1363837,1361309,1371549,1371678,1381992,1386762,1387625,1391901,1389282,1397711
8,Formosa,347837,348455,341668,345732,347174,352290,356077,366612,372342,...,519173,517245,521585,524152,531296,532224,531834,534429,530668,534198
9,Jujuy,479872,481554,473633,480714,480597,483134,485166,494239,501422,...,693463,691531,694804,695522,700736,703578,702279,704940,702867,709345

In [51]:
# Pasar de formato ancho a formato largo
df_acceso_internet_long = df_acceso_internet.melt(
    id_vars="jurisdiccion",
    var_name="periodo",
    value_name="accesos_internet"
)

print(df_acceso_internet_long.shape)
df_acceso_internet_long.head(10)

(2616, 3)

                       jurisdiccion         periodo accesos_internet
0                    Total del país  2016_Diciembre         36970995
1  CABA y provincia de Buenos Aires  2016_Diciembre         19083297
2                         Catamarca  2016_Diciembre           270757
3                             Chaco  2016_Diciembre           704496
4                            Chubut  2016_Diciembre           615952
5                           Córdoba  2016_Diciembre          3246615
6                        Corrientes  2016_Diciembre           727889
7                        Entre Ríos  2016_Diciembre           994765
8                           Formosa  2016_Diciembre           347837
9                             Jujuy  2016_Diciembre           479872

In [52]:
# Separar período en año y mes
df_acceso_internet_long[["anio","mes_texto"]] = df_acceso_internet_long["periodo"].str.split("_", expand=True)

# Convertir año a número
df_acceso_internet_long["anio"] = pd.to_numeric(df_acceso_internet_long["anio"])

df_acceso_internet_long.head(10)

,jurisdiccion,periodo,accesos_internet,anio,mes_texto
0,Total del país,2016_Diciembre,36970995,2016,Diciembre
1,CABA y provincia de Buenos Aires,2016_Diciembre,19083297,2016,Diciembre
2,Catamarca,2016_Diciembre,270757,2016,Diciembre
3,Chaco,2016_Diciembre,704496,2016,Diciembre
4,Chubut,2016_Diciembre,615952,2016,Diciembre
5,Córdoba,2016_Diciembre,3246615,2016,Diciembre
6,Corrientes,2016_Diciembre,727889,2016,Diciembre
7,Entre Ríos,2016_Diciembre,994765,2016,Diciembre
8,Formosa,2016_Diciembre,347837,2016,Diciembre
9,Jujuy,2016_Diciembre,479872,2016,Diciembre

In [53]:
# Mapear meses a números
map_meses = {
    "Enero": 1, "Febrero": 2, "Marzo": 3, "Abril": 4,
    "Mayo": 5, "Junio": 6, "Julio": 7, "Agosto": 8,
    "Septiembre": 9, "Octubre": 10, "Noviembre": 11, "Diciembre": 12
}

df_acceso_internet_long["mes"] = df_acceso_internet_long["mes_texto"].map(map_meses)

df_acceso_internet_long.head(10)

,jurisdiccion,periodo,accesos_internet,anio,mes_texto,mes
0,Total del país,2016_Diciembre,36970995,2016,Diciembre,12.0
1,CABA y provincia de Buenos Aires,2016_Diciembre,19083297,2016,Diciembre,12.0
2,Catamarca,2016_Diciembre,270757,2016,Diciembre,12.0
3,Chaco,2016_Diciembre,704496,2016,Diciembre,12.0
4,Chubut,2016_Diciembre,615952,2016,Diciembre,12.0
5,Córdoba,2016_Diciembre,3246615,2016,Diciembre,12.0
6,Corrientes,2016_Diciembre,727889,2016,Diciembre,12.0
7,Entre Ríos,2016_Diciembre,994765,2016,Diciembre,12.0
8,Formosa,2016_Diciembre,347837,2016,Diciembre,12.0
9,Jujuy,2016_Diciembre,479872,2016,Diciembre,12.0

In [54]:
# Aseguro que accesos_internet sea numerico
df_acceso_internet_long["accesos_internet"] = pd.to_numeric(df_acceso_internet_long["accesos_internet"], errors="coerce")

In [55]:
# Ordenar
df_acceso_internet_long = df_acceso_internet_long.sort_values(["jurisdiccion", "anio", "mes"]).reset_index(drop=True)

In [56]:
# Calcular variacion anual por provincia
df_acceso_internet_long["variacion_acceso_internet_pct"]= df_acceso_internet_long.groupby("jurisdiccion")["accesos_internet"].pct_change(periods=12)*100

In [57]:
# Pasar a anual quedandome con diciembre de cada año
df_acceso_internet_anual = df_acceso_internet_long[
    df_acceso_internet_long["mes"] == 12
][
    ["jurisdiccion", "anio", "variacion_acceso_internet_pct"]
].copy()

df_acceso_internet_anual = df_acceso_internet_anual.sort_values(
    ["jurisdiccion", "anio"]
).reset_index(drop=True)
df_acceso_internet_anual

                         jurisdiccion  anio  variacion_acceso_internet_pct
0    CABA y provincia de Buenos Aires  2016                            NaN
1    CABA y provincia de Buenos Aires  2017                       4.281205
2    CABA y provincia de Buenos Aires  2018                      -0.084572
3    CABA y provincia de Buenos Aires  2019                       3.259377
4    CABA y provincia de Buenos Aires  2020                      -0.906055
..                                ...   ...                            ...
235                           Tucumán  2021                       6.653421
236                           Tucumán  2022                       5.440594
237                           Tucumán  2023                       7.211181
238                           Tucumán  2024                       3.241636
239                           Tucumán  2025                       3.655636

[240 rows x 3 columns]

In [58]:
# Guardar el dataframe procesado
df_acceso_internet_anual.to_csv(
    r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/processed/INDEC/variacion_accesos_internet_provincias_anual.csv",
    index=False
)