## 1.1 Carga del dataset

In [1]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

# Ruta
patch = "/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/final/dataset_mapa_final.csv"
# Carga
df = pd.read_csv(patch)

df.head()

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,poblacion_2022,tasa_delitos_propiedad_100k,tasa_delitos_propiedad_pct,region,variacion_anual_salarios_pct,variacion_anual_cbt,variacion_empleo_const_pct,mes,variacion_anual_ipim,jurisdiccion,variacion_acceso_internet_pct,Indice_IPC,lat,lon
0,2,ciudad autónoma de buenos aires,2001,comuna 1,2017,17609,221001,7967.837250,7.967837,GBA,27.47,26.77,7.865122,12.0,18.85,ciudad autónoma de buenos aires,4.281205,112.985075,-34.606444,-58.371512
1,2,ciudad autónoma de buenos aires,2001,comuna 1,2018,18374,221001,8313.989529,8.313990,GBA,29.71,52.86,2.804384,12.0,73.50,ciudad autónoma de buenos aires,-0.084572,151.569817,-34.606444,-58.371512
2,2,ciudad autónoma de buenos aires,2001,comuna 1,2019,21721,221001,9828.462315,9.828462,GBA,40.89,52.82,-4.095870,12.0,58.49,ciudad autónoma de buenos aires,3.259377,231.605092,-34.606444,-58.371512
3,2,ciudad autónoma de buenos aires,2001,comuna 1,2020,9773,221001,4422.151936,4.422152,GBA,32.99,39.14,-22.513076,12.0,35.38,ciudad autónoma de buenos aires,-0.906055,325.364358,-34.606444,-58.371512
4,2,ciudad autónoma de buenos aires,2001,comuna 1,2021,13012,221001,5887.756164,5.887756,GBA,53.36,40.47,10.894769,12.0,51.34,ciudad autónoma de buenos aires,5.042552,478.615058,-34.606444,-58.371512

## 1.2 Inspección inicial

In [3]:
print(df.shape)
print(df.columns.to_list())
print(df.info())
df.describe().T

(4072, 20)
['provincia_id', 'provincia_nombre', 'departamento_id', 'departamento_nombre', 'anio', 'delitos_propiedad_hechos', 'poblacion_2022', 'tasa_delitos_propiedad_100k', 'tasa_delitos_propiedad_pct', 'region', 'variacion_anual_salarios_pct', 'variacion_anual_cbt', 'variacion_empleo_const_pct', 'mes', 'variacion_anual_ipim', 'jurisdiccion', 'variacion_acceso_internet_pct', 'Indice_IPC', 'lat', 'lon']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4072 entries, 0 to 4071
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   provincia_id                   4072 non-null   int64
 1   provincia_nombre               4072 non-null   object
 2   departamento_id                4072 non-null   int64
 3   departamento_nombre            4072 non-null   object
 4   anio                           4072 non-null   int64
 5   delitos_propiedad_hechos       4072 non-null   int64
 6   poblacion_2022                 4072 non-null   int64
 7   tasa_delitos_propiedad_100k    4072 non-null   float64
 8   tasa_delitos_propiedad_pct     4072 non-null   float64
 9   region                         4072 non-null   object
 10  variacion_anual_salarios_pct   4072 non-null   float64
 11  variacion_anual_cbt            4072 non-null   float64
 12  variacion_empleo_const_pct     4072 non-null   float64
 13  mes                            4072 non-null   float64
 14  variacion_anual_ipim           4072 non-null   float64
 15  jurisdiccion                   4072 non-null   object
 16  variacion_acceso_internet_pct  4072 non-null   float64
 17  Indice_IPC                     4072 non-null   float64
 18  lat                            4072 non-null   float64
 19  lon                            4072 non-null   float64
dtypes: float64(11), int64(5), object(4)
memory usage: 636.4+ KB
None

,count,mean,std,min,25%,50%,75%,max
provincia_id,4072.0,36.125737,29.252875,2.000000,6.000000,26.000000,62.000000,9.400000e+01
departamento_id,4072.0,36294.216356,29151.016219,2001.000000,6735.000000,26091.000000,62056.000000,9.401400e+04
anio,4072.0,2020.539293,2.296907,2017.000000,2019.000000,2021.000000,2023.000000,2.024000e+03
delitos_propiedad_hechos,4072.0,1788.901768,4766.211710,0.000000,115.000000,363.500000,1371.000000,9.872900e+04
poblacion_2022,4072.0,88637.788065,165512.235441,413.000000,13938.000000,33180.000000,93000.000000,1.837168e+06
tasa_delitos_propiedad_100k,4072.0,1431.010404,1032.389010,0.000000,751.076277,1188.022385,1820.840579,1.099407e+04
tasa_delitos_propiedad_pct,4072.0,1.431010,1.032389,0.000000,0.751076,1.188022,1.820841,1.099407e+01
variacion_anual_salarios_pct,4072.0,72.531758,48.832220,27.470000,32.990000,53.360000,145.470000,1.526800e+02
variacion_anual_cbt,4072.0,81.524047,61.428101,26.770000,40.470000,52.860000,106.620000,2.250800e+02
variacion_empleo_const_pct,4072.0,0.112663,12.803301,-22.513076,-17.002318,6.451770,10.894769,1.625877e+01
mes,4072.0,12.000000,0.000000,12.000000,12.000000,12.000000,12.000000,1.200000e+01
variacion_anual_ipim,4072.0,85.473961,76.424685,18.850000,51.340000,67.100000,94.780000,2.763500e+02
variacion_acceso_internet_pct,4072.0,4.552622,4.229410,-9.613182,1.643462,3.974888,7.971208,1.674056e+01
Indice_IPC,4072.0,1348.303570,2010.376404,112.161883,232.355408,485.768858,1928.985267,6.449677e+03
lat,4072.0,-32.409107,5.450772,-54.770468,-35.371274,-32.317412,-27.888754,-2.213764e+01
lon,4072.0,-62.749967,4.141925,-72.065471,-65.811064,-62.434383,-58.941580,-5.396298e+01

## 1.3 Chequeo de nulos

In [4]:
df.isna().sum().sort_values(ascending=False)

provincia_id                     0
provincia_nombre                 0
departamento_id                  0
departamento_nombre              0
anio                             0
delitos_propiedad_hechos         0
poblacion_2022                   0
tasa_delitos_propiedad_100k      0
tasa_delitos_propiedad_pct       0
region                           0
variacion_anual_salarios_pct     0
variacion_anual_cbt              0
variacion_empleo_const_pct       0
mes                              0
variacion_anual_ipim             0
jurisdiccion                     0
variacion_acceso_internet_pct    0
Indice_IPC                       0
lat                              0
lon                              0
dtype: int64

## 1.4 Validacion columna "anio"

In [5]:
print(df["anio"].unique())
df["anio"].value_counts().sort_index()

[2017 2018 2019 2020 2021 2022 2023 2024]

anio
2017    501
2018    501
2019    501
2020    501
2021    501
2022    522
2023    523
2024    522
Name: count, dtype: int64

In [6]:
df.groupby(["provincia_nombre", "departamento_nombre", "anio"]).size().value_counts()

1    4072
Name: count, dtype: int64

# 2 Distribución de la variable objetivo

## 2.1 Importo Plotly - modo oscuro

In [7]:
import plotly.io as pio
pio.templates.default = "plotly_dark"

## 2.2 Histograma (distribución general)

In [9]:
fig_distribucion_general = px.histogram(df, x="tasa_delitos_propiedad_100k",
            nbins=50,
            title="Distribución de la tasa de delitos contra la propiedad (100k habitantes)"
)
fig_distribucion_general.show()

fig_distribucion_general.write_html("/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/dashboard/distribucion_general.html")

## 2.3 Boxplot para detectar outliers

In [12]:
fig_boxplot_outliers = px.box(df,
                 y="tasa_delitos_propiedad_100k",
                 title="Boxplot de la tasa de delitos contra la propiedad (100k habitantes)"
)
fig_boxplot_outliers.show()
fig_boxplot_outliers.write_html("/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/dashboard/boxplot_outliers.html")

## 2.4 Histograma por año

In [13]:
fig_distribucion_por_anio = px.histogram(df,
                   x="tasa_delitos_propiedad_100k",
                   facet_col="anio",
                   facet_col_wrap=2,
                   nbins=40,
                   opacity=0.6,
                   title="Distribución de la tasa de delitos contra la propiedad por año")
fig_distribucion_por_anio.show()
fig_distribucion_por_anio.write_html("/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/dashboard/distribucion_por_anio.html")

## 📊 Análisis de la distribución de la tasa de delitos contra la propiedad

### 1. Distribución general (Histograma)

La distribución de la variable `tasa_delitos_propiedad_100k` presenta una **fuerte asimetría positiva (sesgo a la derecha)**.  
La mayoría de los departamentos se concentran en valores relativamente bajos (aprox. entre 500 y 2000 delitos por cada 100.000 habitantes), mientras que existe una **cola larga hacia valores altos**, alcanzando incluso valores superiores a 10.000.

Esto indica que:
- La mayor parte del territorio presenta niveles moderados de delito.
- Existen pocos casos extremos con tasas muy elevadas.

---

### 2. Identificación de outliers (Boxplot)

El boxplot confirma la presencia de **numerosos valores atípicos (outliers)** en la parte superior de la distribución.

Observaciones:
- La **mediana** se encuentra en valores relativamente bajos dentro del rango total.
- La **dispersión es amplia**, especialmente hacia valores altos.
- Se observan muchos puntos fuera del rango intercuartílico, lo que refuerza la idea de que algunos departamentos presentan niveles de delito significativamente superiores al resto.

Esto sugiere:
- Alta heterogeneidad territorial.
- Posibles casos particulares (grandes ciudades o zonas específicas) que distorsionan la distribución.

---

### 3. Distribución por año (Histograma comparado)

Al analizar la distribución por año:

- Las curvas de los distintos años son **muy similares entre sí**.
- No se observa un desplazamiento claro hacia la derecha o izquierda a lo largo del tiempo.
- La forma de la distribución se mantiene estable (mismo sesgo y dispersión).

Esto indica que:
- La **estructura del fenómeno delictivo es relativamente estable en el tiempo**.
- No hay cambios abruptos en la distribución general de tasas entre 2017 y 2024.
- Las diferencias interanuales, si existen, son más sutiles y no alteran la forma global.

---

## 🧠 Conclusión general

El análisis exploratorio muestra que:

- La tasa de delitos contra la propiedad presenta una **distribución desigual y altamente sesgada**, con pocos departamentos concentrando valores muy altos.
- Existe una **gran variabilidad territorial**, evidenciada por la presencia de múltiples outliers.
- A lo largo del tiempo, la distribución se mantiene **estable en su forma**, lo que sugiere que los patrones estructurales del delito no cambian drásticamente entre los años analizados.

# 3 Evolución temporal

## 3-1 Evolución promedio país

In [14]:
df_anual = df.groupby("anio")["tasa_delitos_propiedad_100k"].mean().reset_index()
df_anual

   anio  tasa_delitos_propiedad_100k
0  2017                  1221.268304
1  2018                  1295.591173
2  2019                  1468.981853
3  2020                  1187.656480
4  2021                  1371.296509
5  2022                  1461.524077
6  2023                  1651.482778
7  2024                  1765.309098

In [15]:
fig_evolucion_anual = px.line(df_anual,
              x="anio",
              y="tasa_delitos_propiedad_100k",
              markers=True,
              title="Evolución anual de la tasa de delitos contra la propiedad (100k habitantes)")
fig_evolucion_anual.show()
fig_evolucion_anual.write_html("/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/dashboard/evolucion_anual.html")

## 3.2 Evolución por región

In [16]:
df_region = df.groupby(["anio", "region"])["tasa_delitos_propiedad_100k"].mean().reset_index()

In [17]:
fig_evolucion_region = px.line(
    df_region,
    x="anio",
    y="tasa_delitos_propiedad_100k",
    color="region",
    markers=True,
    title="Evolución de la tasa de delitos por región"
)

fig_evolucion_region.show()
fig_evolucion_region.write_html("/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/dashboard/evolucion_por_region.html")

## 3.3 Evolución de la dispersión

In [19]:
df_box_anio = df.copy()

In [20]:
fig = px.box(
    df_box_anio,
    x="anio",
    y="tasa_delitos_propiedad_100k",
    title="Distribución de tasas por año",
    hover_data=["departamento_nombre", "provincia_nombre"],
)

fig.show()

## 3.4 Evolución de los extremos (Top Departamentos)

In [21]:
top_10 = (
    df.sort_values(['anio', 'tasa_delitos_propiedad_100k'], ascending=[True, False])
      .groupby('anio', group_keys=False)
      .head(10)
)
top_10.head()

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,poblacion_2022,tasa_delitos_propiedad_100k,tasa_delitos_propiedad_pct,region,variacion_anual_salarios_pct,variacion_anual_cbt,variacion_empleo_const_pct,mes,variacion_anual_ipim,jurisdiccion,variacion_acceso_internet_pct,Indice_IPC,lat,lon
0,2,ciudad autónoma de buenos aires,2001,comuna 1,2017,17609,221001,7967.837250,7.967837,GBA,27.47,26.77,7.865122,12.0,18.85,ciudad autónoma de buenos aires,4.281205,112.985075,-34.606444,-58.371512
2584,50,mendoza,50007,mendoza capital,2017,8893,123715,7188.295680,7.188296,Cuyo,27.47,26.77,7.865122,12.0,18.85,mendoza,2.638317,113.153533,-32.882896,-68.893649
16,2,ciudad autónoma de buenos aires,2003,comuna 3,2017,9591,193537,4955.641557,4.955642,GBA,27.47,26.77,7.865122,12.0,18.85,ciudad autónoma de buenos aires,4.281205,112.985075,-34.613843,-58.402651
24,2,ciudad autónoma de buenos aires,2004,comuna 4,2017,11007,227024,4848.386074,4.848386,GBA,27.47,26.77,7.865122,12.0,18.85,ciudad autónoma de buenos aires,4.281205,112.985075,-34.642113,-58.387561
1336,14,córdoba,14014,cordoba capital,2017,71061,1498060,4743.534972,4.743535,Pampeana,27.47,26.77,7.865122,12.0,18.85,córdoba,5.569432,112.744967,-31.416757,-64.183584

In [22]:
fig_distribucion_anio_top_10 = px.box(
    top_10,
    x="anio",
    y="tasa_delitos_propiedad_100k",
    title="Evolución de los departamentos con mayor tasa",
    hover_data=['departamento_nombre', 'provincia_nombre']
)

fig_distribucion_anio_top_10.show()
fig_distribucion_anio_top_10.write_html("/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/dashboard/distribucion_por_anio_top_10.html")

## 📈 Análisis de la evolución temporal de los delitos contra la propiedad

### 1. Evolución promedio a nivel país

El análisis de la tasa promedio anual muestra una **tendencia creciente en el período 2017–2024**, con una interrupción clara en 2020.

Observaciones:
- Entre 2017 y 2019 se observa un **crecimiento sostenido**.
- En 2020 se produce una **caída significativa**, probablemente asociada a las restricciones de movilidad.
- A partir de 2021 se retoma una **tendencia creciente**, alcanzando en 2024 el valor más alto de toda la serie.

Interpretación:
- El fenómeno presenta un comportamiento **cíclico con recuperación post-pandemia**.
- La tendencia general indica un **incremento estructural del delito en el tiempo**.

---

### 2. Evolución por región

El análisis regional permite identificar patrones diferenciados:

- **GBA** se mantiene consistentemente como la región con mayor tasa, con una **brecha creciente respecto al resto**.
- **Cuyo** presenta una tendencia ascendente sostenida.
- **Patagonia y Noroeste** muestran niveles intermedios con crecimiento moderado.
- **Pampeana y Noreste** se mantienen en niveles más bajos, aunque también con incrementos graduales.
- Todas las regiones presentan una **caída en 2020**, seguida de recuperación.
- La jerarquía entre regiones se mantiene relativamente estable en el tiempo.

Interpretación:
- Existen **diferencias estructurales persistentes entre regiones**.
- El crecimiento del delito es un fenómeno **generalizado**, aunque con distinta intensidad.

---

### 3. Distribución de tasas por año (boxplot)

El análisis de la distribución anual muestra:

- Un **desplazamiento progresivo hacia valores más altos** a lo largo del tiempo.
- La **mediana aumenta** de forma sostenida desde 2020 en adelante.
- La dispersión se mantiene relativamente estable, aunque con leve incremento.
- Persisten numerosos **outliers en todos los años**.

Interpretación:
- No solo aumenta el promedio, sino también el **nivel general del delito en la mayoría de los departamentos**.
- La estructura desigual del fenómeno se mantiene en el tiempo.

---

### 4. Evolución de los departamentos con mayor tasa

Este gráfico permite observar el comportamiento de los valores extremos:

- Se observa una **caída en 2020**, consistente con el resto de los análisis.
- A partir de 2021, los valores máximos crecen de forma marcada.
- Entre 2022 y 2024 se registran los **niveles más altos de toda la serie**.
- Los departamentos más críticos no solo se mantienen, sino que **incrementan su nivel de delito**.
- La distancia entre estos y el promedio general parece ampliarse.

Interpretación:
- Existe una **intensificación del problema en los territorios más afectados**.
- Los outliers no son estáticos: evolucionan y tienden a agravarse.

# 4 Análisis territorial

## 4.1 Top 10 departamentos con mayor tasa de delitos contra la propiedad por año

In [23]:
top_10 = df.sort_values(by="tasa_delitos_propiedad_100k", ascending=False).head(25)
top_10[["tasa_delitos_propiedad_100k", "departamento_nombre", "provincia_nombre", "anio"]]

,tasa_delitos_propiedad_100k,departamento_nombre,provincia_nombre,anio
7,10994.067900,comuna 1,ciudad autónoma de buenos aires,2024
6,10651.988000,comuna 1,ciudad autónoma de buenos aires,2023
2,9828.462315,comuna 1,ciudad autónoma de buenos aires,2019
2590,9686.780099,mendoza capital,mendoza,2023
5,9483.667495,comuna 1,ciudad autónoma de buenos aires,2022
2589,8829.972113,mendoza capital,mendoza,2022
2591,8780.665239,mendoza capital,mendoza,2024
1,8313.989529,comuna 1,ciudad autónoma de buenos aires,2018
0,7967.837250,comuna 1,ciudad autónoma de buenos aires,2017
2588,7294.992523,mendoza capital,mendoza,2021
2584,7188.295680,mendoza capital,mendoza,2017
23,6860.186941,comuna 3,ciudad autónoma de buenos aires,2024
22,6688.643515,comuna 3,ciudad autónoma de buenos aires,2023
31,6672.862781,comuna 4,ciudad autónoma de buenos aires,2024
1342,6590.456991,cordoba capital,córdoba,2023
111,6411.677155,comuna 14,ciudad autónoma de buenos aires,2024
55,6368.223125,comuna 7,ciudad autónoma de buenos aires,2024
2586,6316.129814,mendoza capital,mendoza,2019
110,6282.658988,comuna 14,ciudad autónoma de buenos aires,2023
30,6174.237085,comuna 4,ciudad autónoma de buenos aires,2023
21,6140.427929,comuna 3,ciudad autónoma de buenos aires,2022
1343,6122.918975,cordoba capital,córdoba,2024
2585,6106.777674,mendoza capital,mendoza,2018
18,5938.916073,comuna 3,ciudad autónoma de buenos aires,2019
4,5887.756164,comuna 1,ciudad autónoma de buenos aires,2021

In [24]:
# Gráfico
fig = px.bar(
    top_10,
    y="departamento_nombre",
    x="tasa_delitos_propiedad_100k",
    color="provincia_nombre",
    title="Top 25 departamentos con mayor tasa de delitos contra la propiedad (100k habitantes)",
    hover_data=["provincia_nombre", "anio", "tasa_delitos_propiedad_100k"]
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5)
fig.show()

## 4.2 Top departamentos mas seguros

In [25]:
bottom10 = df.sort_values(by="tasa_delitos_propiedad_100k", ascending=True).head(25)

bottom10[["tasa_delitos_propiedad_100k", "departamento_nombre", "provincia_nombre", "anio"]]

,tasa_delitos_propiedad_100k,departamento_nombre,provincia_nombre,anio
2542,0.000000,general san martín,la rioja,2023
2378,0.000000,valle grande,jujuy,2020
2379,0.000000,valle grande,jujuy,2021
2052,0.000000,telsen,chubut,2022
2407,0.000000,curacó,la pampa,2023
2428,0.000000,limay mahuida,la pampa,2024
2532,0.000000,general lamadrid,la rioja,2021
2047,0.000000,telsen,chubut,2017
1989,0.000000,gastre,chubut,2022
2426,0.000000,limay mahuida,la pampa,2022
1990,0.000000,gastre,chubut,2023
2427,0.000000,limay mahuida,la pampa,2023
2406,0.000000,curacó,la pampa,2022
2380,0.000000,valle grande,jujuy,2022
1546,35.612536,berón de astrada,corrientes,2019
2438,35.697287,quemú ouemú,la pampa,2022
2376,40.160643,valle grande,jujuy,2018
1698,59.351095,san martín,corrientes,2019
2415,68.446270,chicalcó,la pampa,2023
2886,75.728891,catán lil,neuquén,2023
2885,75.728891,catán lil,neuquén,2022
1115,79.113924,tordillo,buenos aires,2020
2375,80.321285,valle grande,jujuy,2017
2377,80.321285,valle grande,jujuy,2019
2568,92.893637,san blas de los sauces,la rioja,2017

In [26]:
fig = px.bar(
    bottom10,
    x="tasa_delitos_propiedad_100k",
    y="departamento_nombre",
    color="provincia_nombre",
    orientation="h",
    title="Departamentos con menor tasa de delitos",
    hover_data=["provincia_nombre", "anio", "tasa_delitos_propiedad_100k"]
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5)
fig.show()

## 4.3 Promedio por provincia

In [27]:
df_prov = df.groupby("provincia_nombre")["tasa_delitos_propiedad_100k"].mean().reset_index()
df_prov = df_prov.sort_values(by="tasa_delitos_propiedad_100k", ascending=False)

In [28]:
fig = px.bar(
    df_prov,
    x="tasa_delitos_propiedad_100k",
    y="provincia_nombre",
    orientation="h",
    title="Promedio de tasa de delitos por provincia"
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5,
                  height=700,
                  margin=dict(l=260, r=20, t=80, b=20),
)

fig.show()

## 4.4 Promedio por región

In [29]:
df_region = df.groupby("region")["tasa_delitos_propiedad_100k"].mean().reset_index()

In [30]:
fig = px.bar(
    df_region,
    x="tasa_delitos_propiedad_100k",
    y="region",
    orientation="h",
    title="Promedio de tasa de delitos por región",
    hover_data=["tasa_delitos_propiedad_100k", "region"]
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5)
fig.show()

## 4.5 Variabilidad territorial

In [31]:
df_std = df.groupby("provincia_nombre")["tasa_delitos_propiedad_100k"].std().reset_index()

df_std = df_std.sort_values(by="tasa_delitos_propiedad_100k", ascending=False)

In [32]:
fig = px.bar(
    df_std,
    x="tasa_delitos_propiedad_100k",
    y="provincia_nombre",
    orientation="h",
    title="Variabilidad de tasas dentro de cada provincia (desvío estándar)"
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5,
                  height=700,
                  margin=dict(l=260, r=20, t=80, b=20),
)

fig.show()

## 🌍 Análisis territorial de los delitos contra la propiedad en Argentina

### 1. Departamentos con mayor tasa de delitos

El análisis de los departamentos con mayor tasa de delitos revela una **alta concentración en pocos territorios específicos**, destacándose principalmente:

- **Ciudad Autónoma de Buenos Aires (CABA)**, especialmente sus comunas, con valores extremadamente elevados.
- **Mendoza (Capital)** y en menor medida **Córdoba**, que también aparecen en los niveles más altos.
- Existe una **sobrerrepresentación de áreas urbanas densamente pobladas**.
- Las comunas de CABA dominan el ranking, lo que sugiere una **dinámica delictiva distinta a la del resto del país**.
- Hay valores significativamente superiores al promedio nacional, lo que indica **outliers estructurales más que casos aislados**.

---

### 2. Departamentos con menor tasa de delitos

En el extremo opuesto, los departamentos con menor tasa presentan:

- Ubicación principalmente en **provincias con baja densidad poblacional** (La Rioja, La Pampa, Chubut, Jujuy).
- Valores muy bajos en comparación con el resto del país.
- Se observa una **relación inversa entre densidad poblacional y tasa de delitos**.
- Estos territorios tienden a ser **más rurales o menos urbanizados**.
- Refuerzan la idea de una **gran heterogeneidad territorial del fenómeno delictivo**.

---

### 3. Promedio de tasa por provincia

El análisis a nivel provincial muestra una jerarquía clara:

- **CABA lidera ampliamente**, con una tasa promedio muy superior al resto.
- **Mendoza** aparece como la segunda provincia con mayor tasa.
- Luego se observa un grupo intermedio con provincias como **Salta, San Juan, Santa Cruz y Río Negro**.
- En el extremo inferior se encuentran **La Rioja, Corrientes y San Luis**.
- El delito contra la propiedad presenta **patrones estructurales a nivel provincial**.
- No es un fenómeno uniforme: hay provincias con **niveles sistemáticamente más altos**.
- CABA actúa como un **caso atípico dentro del sistema nacional**.

---

### 4. Promedio de tasa por región

A nivel regional, se identifican diferencias claras:

- **GBA (Gran Buenos Aires)** muestra el nivel más alto, muy por encima del resto.
- **Cuyo** también presenta niveles elevados.
- **Patagonia y Noroeste** ocupan posiciones intermedias.
- **Región Pampeana y Noreste** presentan los niveles más bajos.
- Las regiones más urbanizadas y económicamente dinámicas tienden a registrar **mayores tasas de delitos**.
- Se evidencia una **geografía del delito**, donde ciertas regiones concentran mayor riesgo.

---

### 5. Variabilidad interna por provincia (desvío estándar)

Con este gráfico podemos entender la **desigualdad interna dentro de cada provincia**:

- **CABA presenta la mayor variabilidad**, lo que indica fuertes diferencias entre comunas.
- **Mendoza y Salta** también muestran alta dispersión.
- Provincias como **Misiones, Corrientes o San Luis** presentan menor variabilidad.
- Un alto desvío estándar implica que dentro de una misma provincia hay **zonas muy seguras y muy inseguras coexistiendo**.
- Un bajo desvío indica un comportamiento más **homogéneo**.

## 5 Relación con variables externas

## 5.1 Selecciono variables numéricas

In [33]:
cols_modelo = [
    "tasa_delitos_propiedad_100k",
    "Indice_IPC",
    "variacion_anual_salarios_pct",
    "variacion_anual_cbt",
    "variacion_empleo_const_pct",
    "variacion_acceso_internet_pct",
    "variacion_anual_ipim"
]

df_corr = df[cols_modelo]

## 5.2 Matriz de correlación

In [34]:
corr = df_corr.corr()
corr

,tasa_delitos_propiedad_100k,Indice_IPC,variacion_anual_salarios_pct,variacion_anual_cbt,variacion_empleo_const_pct,variacion_acceso_internet_pct,variacion_anual_ipim
tasa_delitos_propiedad_100k,1.000000,0.150210,0.169009,0.134713,-0.011891,-0.030508,0.103922
Indice_IPC,0.150210,1.000000,0.784541,0.430964,-0.418479,-0.032215,0.190321
variacion_anual_salarios_pct,0.169009,0.784541,1.000000,0.875207,-0.022410,0.297262,0.717247
variacion_anual_cbt,0.134713,0.430964,0.875207,1.000000,0.149222,0.326206,0.959343
variacion_empleo_const_pct,-0.011891,-0.418479,-0.022410,0.149222,1.000000,0.471107,0.261294
variacion_acceso_internet_pct,-0.030508,-0.032215,0.297262,0.326206,0.471107,1.000000,0.311977
variacion_anual_ipim,0.103922,0.190321,0.717247,0.959343,0.261294,0.311977,1.000000

## 5.3 Heamap

In [35]:
fig = px.imshow(
    corr,
    text_auto=True,
    aspect="auto",
    title="Matriz de correlación entre variables"
)
fig.update_layout(
                  title_x=0.5,
                  height=700,
                  margin=dict(l=260, r=20, t=80, b=20),
)
fig.show()

In [36]:
# Guardar la figura
fig.write_html(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/dashboard/correlaciones.html")


## 5.1 Delito vs inflación

In [37]:
fig = px.scatter(
    df,
    x="Indice_IPC",
    y="tasa_delitos_propiedad_100k",
    trendline="ols",
    title="Relación entre inflación y tasa de delitos"
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5,
                  margin=dict(l=260, r=20, t=80, b=20),
)
fig.show()

## 5.2 Delito vs salarios

In [38]:
fig = px.scatter(
    df,
    x="variacion_anual_salarios_pct",
    y="tasa_delitos_propiedad_100k",
    trendline="ols",
    title="Relación entre salarios y delito"
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5,
                  margin=dict(l=260, r=20, t=80, b=20),
)
fig.show()

## 3. Delito vs empleo construcción

In [39]:
fig = px.scatter(
    df,
    x="variacion_empleo_const_pct",
    y="tasa_delitos_propiedad_100k",
    trendline="ols",
    title="Relación entre empleo en construcción y delito"
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5,
                  margin=dict(l=260, r=20, t=80, b=20),
)
fig.show()

## 4. Delito vs CBT (pobreza proxy)

In [40]:
fig = px.scatter(
    df,
    x="variacion_anual_cbt",
    y="tasa_delitos_propiedad_100k",
    trendline="ols",
    title="Relación entre costo de vida (CBT) y delito"
)
fig.update_layout(yaxis={'categoryorder':'total ascending'},
                  title_x=0.5,
                  margin=dict(l=260, r=20, t=80, b=20),
)

fig.show()

## 🔗 Análisis de la relación entre variables socioeconómicas y delitos contra la propiedad

### 1. Inflación (IPC) y delito

El gráfico muestra una **relación positiva débil** entre el nivel del índice de precios (IPC) y la tasa de delitos.

Observaciones:
- La línea de tendencia tiene pendiente levemente ascendente.
- Existe una **alta dispersión de los datos**, con muchos valores para un mismo nivel de IPC.
- Se observan agrupamientos por año (bandas verticales), lo que indica que el IPC varía más entre años que entre departamentos.
- A mayor inflación, podría existir una **leve tendencia al aumento del delito**, aunque no es una relación fuerte.
- La inflación por sí sola **no explica significativamente la variabilidad del delito a nivel territorial**.

---

### 2. Salarios y delito

El gráfico presenta una **relación positiva muy débil** entre la variación salarial y la tasa de delitos.

Observaciones:
- La pendiente de la línea de tendencia es levemente positiva.
- La dispersión es alta, similar al caso del IPC.
- Se observan valores extremos de delito en distintos niveles salariales.
- No se evidencia una relación clara entre mejoras salariales y reducción del delito.
- Esto sugiere que el delito **no responde directamente a la evolución de los salarios nominales**, o que el efecto está mediado por otras variables.

---

### 3. Empleo en construcción y delito

Este gráfico muestra una **relación prácticamente nula** entre la variación del empleo en construcción y la tasa de delitos.

Observaciones:
- La línea de tendencia es casi horizontal.
- La nube de puntos no presenta patrón claro.
- Existen valores altos de delito tanto en contextos de crecimiento como de caída del empleo.
- El empleo en construcción, al menos en esta forma agregada, **no parece tener un impacto directo sobre el delito**.
- Es posible que esta variable no capture adecuadamente las dinámicas laborales relevantes para el fenómeno.

---

### 4. Costo de vida (CBT) y delito

El gráfico evidencia una **relación positiva débil a moderada** entre el aumento del costo de vida (CBT) y la tasa de delitos.

Observaciones:
- La pendiente de la línea de tendencia es más marcada que en los otros casos.
- Se mantiene una alta dispersión, pero con una tendencia más visible.
- Los valores más altos de CBT coinciden con niveles más elevados de delito.
- El aumento del costo de vida podría estar **más asociado al incremento del delito** que otras variables analizadas.
- Esto sugiere que variables vinculadas a la **presión económica sobre los hogares** pueden tener mayor relevancia explicativa.

---

## 🧠 Conclusión general del análisis de relaciones

- Las relaciones entre variables macroeconómicas y delito son en general **débiles y con alta dispersión**.
- No se observan vínculos lineales fuertes, lo que indica que el fenómeno es **multicausal y complejo**.